<?php

namespace Backend\AdminBundle\Repository;

/**
 * AdminSetting
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminSetting extends \Doctrine\ORM\EntityRepository
{
}
