<?php

namespace Backend\AdminBundle\Repository;

/**
 * AppTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppTextRepository extends \Doctrine\ORM\EntityRepository
{
}
