<?php

namespace Backend\AdminBundle\Repository;

/**
 * BookingCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingCommentRepository extends \Doctrine\ORM\EntityRepository
{



    public function getCommentsQuantity($reservationID)
    {

        $qb = $this->createQueryBuilder('c');
        $qb->select('count(c.id)');
        $qb->where('c.id = :reservationID')->setParameter("reservationID", $reservationID);
        //$qb->from('ZaysoCoreBundle:Account','account');

        $count = $qb->getQuery()->getSingleScalarResult();

        return $count;

    }
}
