<?php

namespace Backend\AdminBundle\Repository;

/**
 * BookingLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingLogRepository extends \Doctrine\ORM\EntityRepository
{
}
