<?php

namespace Backend\AdminBundle\Repository;

/**
 * CommonAreaReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonAreaReservationRepository extends \Doctrine\ORM\EntityRepository
{
    private function getApiCommonAreaAvailability($commonAreaId)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a, c, cars')
            ->innerJoin('a.commonArea', 'c')
            ->innerJoin('a.commonAreaResevationStatus', 'cars')
            ->where('a.enabled = 1')
            ->andWhere('c.enabled = 1')
            ->andWhere('cars.enabled = 1')
            ->andWhere('c.id = :common_area_id')
            ->setParameter('common_area_id', $commonAreaId)
            ->orderBy('a.createdAt', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
