<?php

namespace Backend\AdminBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * CommonAreaAvailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonAreaAvailabilityRepository extends \Doctrine\ORM\EntityRepository
{



    public function  clearSchedule($commonAreaID){

        $sql = "	DELETE
					FROM 	common_area_availability;
                    WHERE 	common_area_id = {$commonAreaID}";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

    }


    public function getSchedule($commonAreaID)
    {

        $sql = "	SELECT  *
					FROM 	common_area_availability
                    WHERE 	common_area_id = {$commonAreaID}
                    ORDER BY weekday_single, id";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        //print $sql;die;

        $execute = $stmt->fetchAll();


        if (empty($execute)) {
            return "";
        }

        //$('#schedule').jqs('import', []},{ day: 6, periods: [['09:00','14:00'],]}]);
        /*
     $('#schedule3').jqs('import', [
          {
            day: 1,
            periods: [
              ['8:00', '10:00'] // Compact
            ]
          }, {
            day: 2,
            periods: [
              ['20:00', '00:00'],
              ['20:00', '22:00'] // Invalid period, not displayed
            ]
          }, {
            day: 4,
            periods: [
              { // Full
                start: '10:00',
                end: '12:00',
                title: 'A black period',
                backgroundColor: '#000',
                borderColor: '#000',
                textColor: '#fff'
              }
            ]
          }
        ]);
        */


        //$('#schedule').jqs('import', [{ day: 0, periods: [['06:00','07:00']]},{ day: 1, periods: [['06:00','07:00']]},{ day: 2, periods: [['06:00','07:00']]},{ day: 3, periods: [['06:00','07:00']]},{ day: 4, periods: [['06:00','07:00']]},{ day: 5, periods: [['06:00','07:00']]},{ day: 6, periods: [['06:00','07:00']]}]);

        $days = "";


        $arrDays = array();
        foreach ($execute as $row) {

            $day = $row["weekday_single"];

            if (!isset($arrDays[$day])) {

                if ($day > 0 && ($days != "") ) {
                    $days .= "]},";
                }

                $arrDays[$day] = $day;
                $days .= "{ day: " . $day . ",";
                $days .= " periods: [";
            }

            $days .= "['" . $row["hour_from"] . "','" . $row["hour_to"] . "'],";

        }

        $days = "[" . $days . "]}]";

        //print $days;die;

        return $days;
    }



    public function getApiCommonAreaAvailability($commonAreaId)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a, c')
            ->leftJoin('a.commonArea', 'c', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('c', 'a.commonArea'),
                $qb->expr()->eq('c.enabled', '1')
            ))
//            ->where('a.enabled = 1') // ToDo: no field enabled in entity
            ->andWhere('c.id = :common_area_id')
            ->setParameter('common_area_id', $commonAreaId)
            ->orderBy('a.createdAt', 'ASC');

        return $qb->getQuery()->getResult();
    }

}
