<?php

namespace Backend\AdminBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * CommonAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonAreaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApiCommonAreas($complexIds, $pageId = 1, $limit = 10)
    {
        $qb = $this->queryBuilderForApiCommonAreas($complexIds);

        $qb->setFirstResult(($pageId - 1) * $limit)// Offset
        ->setMaxResults($limit)// Limit
        ->orderBy('a.createdAt', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function countApiCommonAreas($complexIds)
    {
        $qb = $this->queryBuilderForApiCommonAreas($complexIds);
        $qb->select('count(a.id)');
        return $qb->getQuery()->getSingleScalarResult();
    }

    private function queryBuilderForApiCommonAreas($complexIds)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a, c, cat')
            ->leftJoin('a.complex', 'c', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('c', 'a.complex'),
                $qb->expr()->eq('c.enabled', '1')
            ))
            ->leftJoin('a.commonAreaType', 'cat', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('cat', 'a.commonAreaType'),
                $qb->expr()->eq('cat.enabled', '1')
            ))
            ->andWhere('a.enabled = 1')
        ;

        if ( count( $complexIds ) > 0 ) {
            $qb->andWhere($qb->expr()->in('c.id', $complexIds));
        } else {
            $qb->andWhere('c.id = 0');
        }

        return $qb;
    }



    
    public function getRequiredDTData($start, $length, $orders, $search, $columns, $filterComplex)
    {
        //print "entra";die;
        // Create Main Query
        $query = $this->createQueryBuilder('e');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        //ENABLED
        $query->andWhere("e.enabled = 1");
        $countQuery->andWhere("e.enabled = 1");


        // Create inner joins


        //complex
        $query->join('e.complex', 'c');
        $countQuery->join('e.complex', 'c');

        if($filterComplex != null){
            $query->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
            $countQuery->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
        }


        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                        {
                            $searchQuery = 'e.id ='. $searchItem;
                            break;
                        }
                    case 'name':
                        {
                            $searchQuery = 'e.name LIKE \'%' . $searchItem . '%\'';
                            break;
                        }

                    case 'complex':
                        {
                            $searchQuery = 'c.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                        {
                            $orderColumn = 'e.id';
                            break;
                        }
                    case 'name':
                        {
                            $orderColumn = 'e.name';
                            break;
                        }

                    case 'complex':
                        {
                            $orderColumn = 'c.complex';
                            break;
                        }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }
    
}
