<?php

namespace Backend\AdminBundle\Repository;

/**
 * CommonAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonAreaRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getRequiredDTData($start, $length, $orders, $search, $columns, $filterComplex)
    {
        //print "entra";die;
        // Create Main Query
        $query = $this->createQueryBuilder('e');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        //ENABLED
        $query->andWhere("e.enabled = 1");
        $countQuery->andWhere("e.enabled = 1");


        // Create inner joins

        //sector
        $query->join('e.commonAreaType', 's');
        $countQuery->join('e.commonAreaType', 's');


        //complex
        $query->join('s.complex', 'c');
        $countQuery->join('s.complex', 'c');

        if($filterComplex != null){
            $query->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
            $countQuery->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
        }


        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                        {
                            $searchQuery = 'e.id ='. $searchItem;
                            break;
                        }
                    case 'name':
                        {
                            $searchQuery = 'e.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'description':
                        {
                            $searchQuery = 'e.description LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                        
                    case 'regulation':
                        {
                            $searchQuery = 'e.regulation LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'termCondition':
                        {
                            $searchQuery = 'e.termCondition LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                        
                    case 'price':
                        {
                            $searchQuery = 'e.price LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'reservationHourPeriod':
                        {
                            $searchQuery = 'e.reservationHourPeriod LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'requiredPayment':
                        {
                            $searchQuery = 'e.requiredPayment LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'hasEquipment':
                        {
                            $searchQuery = 'e.hasEquipment LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'equipmentDescription':
                        {
                            $searchQuery = 'e.equipmentDescription LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                    case 'complex':
                        {
                            $searchQuery = 'c.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'commonAreaType':
                        {
                            $searchQuery = 's.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                        {
                            $orderColumn = 'e.id';
                            break;
                        }
                    case 'name':
                        {
                            $orderColumn = 'e.name';
                            break;
                        }
                    case 'description':
                        {
                            $orderColumn = 'e.description';
                            break;
                        }
                        
                    case 'regulation':
                        {
                            $orderColumn = 'e.regulation';
                            break;
                        }
                    case 'termCondition':
                        {
                            $orderColumn = 'e.termCondition';
                            break;
                        }
                        
                    case 'price':
                        {
                            $orderColumn = 'e.price';
                            break;
                        }
                    case 'reservationHourPeriod':
                        {
                            $orderColumn = 'e.reservationHourPeriod';
                            break;
                        }
                    case 'requiredPayment':
                        {
                            $orderColumn = 'e.requiredPayment';
                            break;
                        }
                    case 'hasEquipment':
                        {
                            $orderColumn = 'e.hasEquipment';
                            break;
                        }
                    case 'equipmentDescription':
                        {
                            $orderColumn = 'e.equipmentDescription';
                            break;
                        }

                    case 'complex':
                        {
                            $orderColumn = 'c.complex';
                            break;
                        }
                    case 'commonAreaType':
                        {
                            $orderColumn = 's.commonAreaType';
                            break;
                        }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }
    
}
