<?php

namespace Backend\AdminBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * CommonAreaReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonAreaReservationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApiCommonAreaAvailability($commonAreaId, $date)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a, c, cars')
            ->leftJoin('a.commonArea', 'c', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('c', 'a.commonArea'),
                $qb->expr()->eq('c.enabled', '1')
            ))
            ->leftJoin('a.commonAreaReservationStatus', 'cars', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('cars', 'a.commonAreaReservationStatus'),
                $qb->expr()->eq('cars.enabled', '1')
            ))
            ->where('a.enabled = 1')
            ->andWhere('c.id = :common_area_id')
            ->setParameter('common_area_id', $commonAreaId)
            ->andWhere('a.reservationDateFrom >= :myDateStart AND a.reservationDateTo <= :myDateEnd')
            ->setParameter('myDateStart', date("Y-m-d H:i:s", strtotime($date." 00:00:00")))
            ->setParameter('myDateEnd', date("Y-m-d H:i:s", strtotime($date." 23:59:59")))

            ->orderBy('a.createdAt', 'ASC');


        //$query=$qb->getQuery();
        // SHOW SQL:
        //echo $query->getSQL();
        // Show Parameters:
        //echo $query->getParameters();
        //die;

        return $qb->getQuery()->getResult();
    }



    public function getRequiredDTData($start, $length, $orders, $search, $columns, $filterComplex, $dateConditions, $businessLocale, $property = null)
    {

        // Create Main Query
        $query = $this->createQueryBuilder('e');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');


        //ENABLED
        $query->andWhere("e.enabled = 1");
        $countQuery->andWhere("e.enabled = 1");


        // Create inner joins

        //common area
        $query->join('e.commonArea', 'ca');
        $countQuery->join('e.commonArea', 'ca');

        //reserved by
        $query->join('e.reservedBy', 'u');
        $countQuery->join('e.reservedBy', 'u');


        //reservation status
        $query->join('e.commonAreaReservationStatus', 's');
        $countQuery->join('e.commonAreaReservationStatus', 's');


        //complex
        $query->join('ca.complex', 'c');
        $countQuery->join('ca.complex', 'c');

        //property
        $query->join('e.property', 'p');
        $countQuery->join('e.property', 'p');

        if($filterComplex != null){
            $query->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
            $countQuery->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
        }

        if($property != null){
            $query->andWhere('p.id = :propertyID')->setParameter('propertyID', intval($property));
            $countQuery->andWhere('p.id = :propertyID')->setParameter('propertyID', intval($property));
        }


        // Other conditions than the ones sent by the Ajax call ?
        if ($dateConditions === null)
        {


            // No
            // However, add a "always true" condition to keep an uniform treatment in all cases
            //$query->andWhere("1=1");
            //$countQuery->andWhere("1=1");

            /*
             * SELECT 	*
                FROM 	common_area_reservation
                WHERE 	DATE(created_at) >= DATE(NOW() - INTERVAL 1 MONTH)
                OR 		common_area_reservation_status_id = 1;
             */

            //FILTER
            $now = gmdate("Y-m-d");
            $defaultDate = gmdate('Y-m-d H:i:s', strtotime($now . ' -31 day'));
            //var_dump($defaultDate);die;
            $query->andWhere("e.createdAt >= :date")
                    ->setParameter(':date', $defaultDate);
            $countQuery->andWhere("e.createdAt >= :date")
                ->setParameter(':date', $defaultDate);

        }
        else
        {

            // Add date condition

            $query->andWhere('e.reservationDateFrom >= :startDate AND e.reservationDateTo <= :endDate')
                ->setParameter('startDate', date("Y-m-d H:i:s", strtotime($dateConditions["start"])) )
                ->setParameter('endDate', date('Y-m-d H:i:s', strtotime($dateConditions["end"] . ' +1 day')));
            //$countQuery->where($otherConditions);
            $countQuery->andWhere('e.reservationDateFrom >= :startDate AND e.reservationDateTo <= :endDate')
                ->setParameter('startDate', date("Y-m-d H:i:s", strtotime($dateConditions["start"])) )
                ->setParameter('endDate', date('Y-m-d H:i:s', strtotime($dateConditions["end"] . ' +1 day')));


        }

        //var_dump(date('Y-m-d H:i:s', strtotime($dateConditions["end"] . ' +1 day')));die;

        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                        {
                            $searchQuery = 'e.id ='. $searchItem;
                            break;
                        }
                    case 'user':
                        {
                            $searchQuery = 'u.name LIKE \'%' . $searchItem . '%\'';
                            break;
                        }

                    case 'complex':
                        {
                            $searchQuery = 'c.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                    case 'property':
                        {
                            $searchQuery = 'p.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'commonArea':
                        {
                            $searchQuery = 'ca.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                    case 'eventDate':
                        {
                            $searchQuery = 'e.reservationDateFrom LIKE \'%'.$searchItem.'%\''. ' OR '.'e.reservationDateTo LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                    case 'approved':
                        {
                            $searchQuery = 'e.approved LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                    case 'requested':
                        {
                            $searchQuery = 'e.createdAt LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                    case 'status':
                        {
                            if($businessLocale == "es"){
                                $searchQuery = 's.nameES LIKE \'%'.$searchItem.'%\'';
                            }
                            else{
                                $searchQuery = 's.nameEN LIKE \'%'.$searchItem.'%\'';
                            }
                            break;
                        }
                    /*
                    case 'dateFrom':
                        {
                            $searchQuery = "e.reservationDateFrom = '".$searchItem."'";
                            break;
                        }
                    */


                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }



        // Limit
        $query->setFirstResult($start)->setMaxResults($length);
        //$query->orderBy('e.reservationDateFrom', 'desc');


        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                        {
                            $orderColumn = 'e.id';
                            break;
                        }
                    case 'user':
                        {
                            $orderColumn = 'u.name';
                            break;
                        }

                    case 'commonArea':
                        {
                            $orderColumn = 'ca.name';
                            break;
                        }


                    case 'complex':
                        {
                            $orderColumn = 'c.name';
                            break;
                        }

                    case 'property':
                        {
                            $orderColumn = 'p.name';
                            break;
                        }

                    case 'approved':
                        {
                            $orderColumn = 'e.approved';
                            break;
                        }

                    case 'requested':
                        {
                            $orderColumn = 'e.createdAt';
                            break;
                        }
                    case 'status':
                        {
                            if($businessLocale == "es"){
                                $orderColumn = 's.nameES';
                            }
                            else{
                                $orderColumn = 's.nameEN';
                            }
                            break;

                        }

                    case 'dateFrom':
                        {
                            $orderColumn = 'e.reservationDateFrom';
                            break;
                        }

                    case 'dateTo':
                        {
                            $orderColumn = 'e.reservationDateTo';
                            break;
                        }
                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        /*
        $sql=$query->getQuery()->getSQL();
        print $sql;die;
        */

        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }


    public function getSchedule($filters){


        $strFilter = "";
        if($filters != null){

            $inComplex = "";
            foreach ($filters as $k => $v){
                $inComplex .= $inComplex == "" ? $k : ",".$k;
            }


            $strFilter = " AND c.id IN($inComplex)";
        }

        $sql = "	SELECT  r.id, 
	                        DATE_FORMAT(r.reservation_date_from, '%Y-%m-%dT%H:%i:%s') reservation_date_from , DATE_FORMAT(r.reservation_date_to, '%Y-%m-%dT%H:%i:%s') reservation_date_to,
	                        u.name username, 
	                        ca.name common_area, c.name complex
					FROM 	common_area_reservation r
					    INNER JOIN common_area ca ON (r.common_area_id = ca.id)
					    INNER JOIN complex c ON (ca.complex_id = c.id)
					    INNER JOIN user u ON (u.id = r.reserved_by)
                    WHERE 	common_area_reservation_status_id = 2 /*APPROVED*/
                    {$strFilter}
                    ORDER BY r.id";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        //print $sql;die;

        $execute = $stmt->fetchAll();

        if (empty($execute)) {
            return "";
        }

        /*
        {
            title: 'Meeting',
                        start: '2019-04-12T10:30:00',
                        end: '2019-04-12T12:30:00'
        },
        */


        $strReturn = "";


        foreach ($execute as $row) {
            $strTemp = "{ title: '".$row["complex"]."/ ".$row["common_area"]."/ ".$row["username"]."',";
            $strTemp .= "start: '".$row["reservation_date_from"]."',";
            $strTemp .= "end: '".$row["reservation_date_to"]."'},";


            $strReturn .= $strTemp;
        }


        return $strReturn;


    }


    //esta funcion valida si hay otras reservaciones con horario traslapado y aprueba la enviada y las demas las rechaza
    public function validateSchedule($start, $end, $commonAreaID, $reservationID){


        $sql = "	SELECT 	id, reservation_date_from, reservation_date_to
                    FROM 	common_area_reservation
                    WHERE	common_area_id = {$commonAreaID}
                    AND		(reservation_date_from < '{$end}'
                    AND 	reservation_date_to > '{$start}')";
                    //AND     common_area_reservation_status_id = 1

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        //print $sql;die;

        $execute = $stmt->fetchAll();

        foreach ($execute as $row) {

            if($row["id"] == $reservationID){
                //APPROVED
                $sqlUpdate = "  UPDATE  common_area_reservation
                                SET     common_area_reservation_status_id = 2
                                WHERE   id = ".$row["id"];
            }
            else{
                //DENIED
                $sqlUpdate = "  UPDATE  common_area_reservation
                                SET     common_area_reservation_status_id = 3
                                WHERE   id = ".$row["id"];
            }

            $stmtUpdate = $this->getEntityManager()->getConnection()->prepare($sqlUpdate);
            $stmtUpdate->execute();

        }

    }


    public function getNotification($userID, $complexFilters){

        $arrReturn = array();
        $strFilter = "";
        $in = "";
        if(!empty($complexFilters)){
            foreach ($complexFilters as $key => $value) {
                $in .= $in == "" ? $value : ",".$value;
            }

        }
        $strFilter = " AND ca.complex_id IN({$in}) ";


        $sql = "	SELECT 	n.id, n.created_at, n.description, n.notification_type_id, 
	                        car.id reservation_id
                    FROM 	user_notification n
                        INNER JOIN common_area_reservation car ON (n.common_area_reservation_id = car.id)
                        INNER JOIN common_area ca ON (car.common_area_id = ca.id)
                    
                    WHERE n.notification_type_id = 1
                    AND n.is_read = 0
                    $strFilter
                    ORDER BY n.id";



        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();

        foreach ($execute as $row) {
            $arrReturn[$row["id"]] = array();
            $arrReturn[$row["id"]]["description"] = $row["description"];
            $arrReturn[$row["id"]]["created_at"] = $row["created_at"];
            $arrReturn[$row["id"]]["reservation_id"] = $row["reservation_id"];
            $arrReturn[$row["id"]]["type"] = $row["notification_type_id"];
        }

        return $arrReturn;

    }

    //markAllNotificationRead

    public function markAllNotificationRead($userID, $complexFilters){

        $arrReturn = array();
        $strFilter = "";
        $in = "";
        if(!empty($complexFilters)){
            foreach ($complexFilters as $key => $value) {
                $in .= $in == "" ? $value : ",".$value;
            }

        }
        $strFilter = " AND ca.complex_id IN({$in}) ";

        //COMMON AREA RESERVATION
        $sql = "	SELECT 	n.id
                    FROM 	user_notification n
                        INNER JOIN common_area_reservation car ON (n.common_area_reservation_id = car.id)
                        INNER JOIN common_area ca ON (car.common_area_id = ca.id)
                    WHERE n.notification_type_id = 1
                    AND n.is_read = 0
                    $strFilter
                    ORDER BY n.id";



        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();

        foreach ($execute as $row) {

            $tempID = intval($row["id"]);
            $sqlUpdate = "  UPDATE    user_notification
                            SET  is_read = 1
                            WHERE id = {$tempID}";

            $stmt = $this->getEntityManager()->getConnection()->prepare($sqlUpdate);
            $stmt->execute();

        }


        /////TICKET NOTIFICATIONS
        ///
        $strFilter = " AND t.complex_id IN({$in}) ";
        $sql = "	SELECT 	t.id 
                    FROM 	user_notification n
                        INNER JOIN ticket t ON (n.ticket_id = t.id)
                    WHERE n.notification_type_id = 1
                    AND n.is_read = 0
                    $strFilter
                    ORDER BY n.id";



        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();

        foreach ($execute as $row) {

            $tempID = intval($row["id"]);
            $sqlUpdate = "  UPDATE    user_notification
                            SET  is_read = 1
                            WHERE id = {$tempID}";

            $stmt = $this->getEntityManager()->getConnection()->prepare($sqlUpdate);
            $stmt->execute();

        }


        return true;

    }



    //getRequiredDTData($start, $length, $orders, $search, $columns, $filterComplex, null, $this->translator->getLocale());



    public function getStats($complexID){

        $arrReturn = array();

        //total
        $countTotal = "     SELECT  COUNT(r.id) quantity
                            FROM 	common_area_reservation r 
                                INNER JOIN common_area a ON (r.common_area_id = a.id)
                            WHERE   r.enabled = 1
                            AND     a.complex_id = {$complexID}";
        //AND     t.complex_id = {$complexID}

        $stmt = $this->getEntityManager()->getConnection()->prepare($countTotal);
        $stmt->execute();
        $execute = $stmt->fetchAll();

        $arrReturn["total"] = $execute[0]["quantity"];

        //approved
        $countApproved = "     SELECT  COUNT(r.id) quantity
                            FROM 	common_area_reservation r 
                                INNER JOIN common_area a ON (r.common_area_id = a.id)
                            WHERE   r.enabled = 1
                            AND     a.complex_id = {$complexID}
                            AND      r.common_area_reservation_status_id = 2";

        $stmt = $this->getEntityManager()->getConnection()->prepare($countApproved);
        $stmt->execute();
        $execute = $stmt->fetchAll();

        $arrReturn["approved"] = $execute[0]["quantity"];

        //rejected
        $countApproved = "     SELECT  COUNT(r.id) quantity
                            FROM 	common_area_reservation r 
                                INNER JOIN common_area a ON (r.common_area_id = a.id)
                            WHERE   r.enabled = 1
                            AND     a.complex_id = {$complexID}
                            AND      r.common_area_reservation_status_id = 3";

        $stmt = $this->getEntityManager()->getConnection()->prepare($countApproved);
        $stmt->execute();
        $execute = $stmt->fetchAll();

        $arrReturn["rejected"] = $execute[0]["quantity"];

        return $arrReturn;

    }


}
