<?php

namespace Backend\AdminBundle\Repository;

/**
 * CommonAreaPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonAreaPhotoRepository extends \Doctrine\ORM\EntityRepository
{

    private function getApiCommonAreas($commonAreaIds)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a, c')
            ->innerJoin('a.commonArea', 'c')
            ->where('a.enabled = 1')
            ->andWhere('c.enabled = 1');

        if ( count( $commonAreaIds ) > 0 ) {
            $qb->andWhere($qb->expr()->in('c.id', $commonAreaIds));
        } else {
            $qb->andWhere('c.id = 0');
        }

        return $qb;
    }

}
