<?php

namespace Backend\AdminBundle\Repository;

/**
 * CommonAreaPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonAreaPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
