<?php

namespace Backend\AdminBundle\Repository;

/**
 * CommonAreaAvailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonAreaAvailabilityRepository extends \Doctrine\ORM\EntityRepository
{
}
