<?php

namespace Backend\AdminBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * CommonAreaAvailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonAreaAvailabilityRepository extends \Doctrine\ORM\EntityRepository
{



    public function  clearSchedule($commonAreaID){

        //var_dump($commonAreaID);die;

        $sql = "	DELETE
					FROM 	common_area_availability
                    WHERE 	common_area_id = {$commonAreaID}";

        //var_dump($sql);die;

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

    }


    public function getSchedule($commonAreaID)
    {

        $sql = "	SELECT  *
					FROM 	common_area_availability
                    WHERE 	common_area_id = {$commonAreaID}
                    ORDER BY weekday_single, id";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        //print $sql;die;

        $execute = $stmt->fetchAll();


        if (empty($execute)) {
            return "";
        }

        //$('#schedule').jqs('import', []},{ day: 6, periods: [['09:00','14:00'],]}]);
        /*
     $('#schedule3').jqs('import', [
          {
            day: 1,
            periods: [
              ['8:00', '10:00'] // Compact
            ]
          }, {
            day: 2,
            periods: [
              ['20:00', '00:00'],
              ['20:00', '22:00'] // Invalid period, not displayed
            ]
          }, {
            day: 4,
            periods: [
              { // Full
                start: '10:00',
                end: '12:00',
                title: 'A black period',
                backgroundColor: '#000',
                borderColor: '#000',
                textColor: '#fff'
              }
            ]
          }
        ]);
        */


        //$('#schedule').jqs('import', [{ day: 0, periods: [['06:00','07:00']]},{ day: 1, periods: [['06:00','07:00']]},{ day: 2, periods: [['06:00','07:00']]},{ day: 3, periods: [['06:00','07:00']]},{ day: 4, periods: [['06:00','07:00']]},{ day: 5, periods: [['06:00','07:00']]},{ day: 6, periods: [['06:00','07:00']]}]);

        $days = "";


        $arrDays = array();
        foreach ($execute as $row) {

            $day = $row["weekday_single"];

            if (!isset($arrDays[$day])) {

                if ($day > 0 && ($days != "") ) {
                    $days .= "]},";
                }

                $arrDays[$day] = $day;
                $days .= "{ day: " . $day . ",";
                $days .= " periods: [";
            }

            $days .= "['" . $row["hour_from"] . "','" . $row["hour_to"] . "'],";

        }

        $days = "[" . $days . "]}]";

        //print $days;die;

        return $days;
    }



    public function getApiCommonAreaAvailability($commonAreaId)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a, c')
            ->leftJoin('a.commonArea', 'c', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('c', 'a.commonArea'),
                $qb->expr()->eq('c.enabled', '1')
            ))
            ->andWhere('c.id = :common_area_id')
            ->setParameter('common_area_id', $commonAreaId)
            ->orderBy('a.createdAt', 'ASC');

        return $qb->getQuery()->getResult();
    }




    public function getCommonAreaAvailability($commonAreaID, $date){

        //$filterDay = $singleDay != null ? " AND weekday_single = {$singleDay}" : "";
        //Convert the date string into a unix timestamp.
        $unixTimestamp = strtotime($date);

        //Get the day of the week using PHP's date function.
        $dayOfWeek = date("N", $unixTimestamp);
        //var_dump($dayOfWeek);die;
        $myDay = intval($dayOfWeek)-1;


        $sql = "	SELECT  *
					FROM 	common_area_availability
                    WHERE 	common_area_id = {$commonAreaID}
                    AND     weekday_single = {$myDay}";

        //var_dump($sql);die;

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();

        $arrAvailability = array();
        $index = 0;
        foreach ($execute as $key => $value){
            //var_dump($value);die;

            $arrAvailability[$index] = array();
            $arrAvailability[$index]["hour_from"] = $value["hour_from"];
            $arrAvailability[$index]["hour_to"] = $value["hour_to"];
            $index++;
        }



        $sqlReservation = "	SELECT  *
                            FROM 	common_area_reservation
                            WHERE 	common_area_id = {$commonAreaID}
                            AND     common_area_reservation_status_id != 3
                            AND     enabled = 1
                            AND     DATE(reservation_date_to) <= '{$date}' AND  DATE(reservation_date_from) >= '{$date}' ";

        //var_dump($sqlReservation);die;

        $stmt = $this->getEntityManager()->getConnection()->prepare($sqlReservation);
        $stmt->execute();

        $execute = $stmt->fetchAll();

        $arrReservation = array();
        $arrSchedule = array();
        $index = 0;
        foreach ($execute as $key => $value){
            //var_dump($value);die;

            $arrReservation[$index] = array();
            $arrReservation[$index]["hour_from"] = $hourFrom = substr($value["reservation_date_from"], 11, 5);
            $arrReservation[$index]["hour_to"] = $hourTo = substr($value["reservation_date_to"], 11, 5);

            foreach ($arrAvailability as $key => $availability){
                //var_dump($availability);

                if($hourFrom == $availability["hour_from"] && $hourTo == $availability["hour_to"] ){
                    //$arrSchedule[$index]["hour_from"] = $availability["hour_from"];
                    //$arrSchedule[$index]["hour_to"] = $availability["hour_to"];
                    unset($arrAvailability[$key]);
                }

            }


            $index++;
        }

        //print "<pre>";
        //var_dump($arrAvailability);die;
        return $arrAvailability;

    }

}
