<?php

namespace Backend\AdminBundle\Repository;

/**
 * CommonAreaReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonAreaReservationRepository extends \Doctrine\ORM\EntityRepository
{
}
