<?php

namespace Backend\AdminBundle\Repository;

/**
 * ComplexPollRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplexPollRepository extends \Doctrine\ORM\EntityRepository
{
}
