<?php

namespace Backend\AdminBundle\Repository;

/**
 * ComplexFaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplexFaqRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApiFaqs( $complexId, $pageId = 1, $limit = 10 )
    {
        $qb = $this->getGenericApiFaqs($complexId);

        $qb->setFirstResult(($pageId - 1) * $limit)// Offset
            ->setMaxResults($limit); // Limit

        return $qb->getQuery()->getResult();
    }

    public function countApiFaqs( $complexId )
    {
        $qb = $this->getGenericApiFaqs($complexId);

        $qb->select('count(a.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getGenericApiFaqs( $complexId )
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a')
            ->innerJoin('a.complex', 'c')
            ->where('a.enabled = 1')
            ->andWhere('c.enabled = 1')
            ->andWhere('c.id = :complexId')
            ->setParameter('complexId', $complexId)
            ->orderBy('a.orderList', 'ASC')
        ;

        return $qb;
    }


     public function getRequiredDTData($start, $length, $orders, $search, $columns, $otherConditions, $filterComplex)
    {
        //print "entra";die;
        // Create Main Query
        $query = $this->createQueryBuilder('e');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        // Create inner joins
        $query->join('e.complex', 'c');
        $countQuery->join('e.complex', 'c');


        //ENABLED
        $query->andWhere("e.enabled = 1");
        $countQuery->andWhere("e.enabled = 1");

        $query->andWhere("c.enabled = 1");
        $countQuery->andWhere("c.enabled = 1");



        if($filterComplex != null){
            $query->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
            $countQuery->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
        }


        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                        {
                            $searchQuery = 'e.id ='. $searchItem;
                            break;
                        }

                    case 'complex':
                        {
                            $searchQuery = 'c.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }


                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                        {
                            $orderColumn = 'e.id';
                            break;
                        }

                    case 'complex':
                        {
                            $orderColumn = 'c.name';
                            break;
                        }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }


}
