<?php

namespace Backend\AdminBundle\Repository;

/**
 * ComplexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplexRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApiFaqs( $complexId )
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a, b')
            ->innerJoin('a.business', 'b')
            ->where('a.enabled = 1')
            ->andWhere('b.enabled = 1')
            ->andWhere('a.id = :complexId')
            ->setParameter('complexId', $complexId)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }


    public function getComplexByUser($userID)
    {

        $sql = "	SELECT  c.id, c.name
					FROM    user_complex uc
					    INNER JOIN complex c ON(c.id = uc.complex_id)
					WHERE   uc.user_id = {$userID}
					ORDER BY c.name";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();
        $arrReturn = array();
        foreach ($execute as $row) {
            $arrReturn[$row["name"]] = $row["id"];
        }

        return $arrReturn;

    }


    public function getRequiredDTData($start, $length, $orders, $search, $columns, $filterComplex, $businessLocale, $role)
    {
        //print "entra";die;
        // Create Main Query
        $query = $this->createQueryBuilder('e');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        //ENABLED
        if($role != 'SUPER ADMIN'){
            $query->andWhere("e.enabled = 1");
            $countQuery->andWhere("e.enabled = 1");

        }


        // Create inner joins

        //complex Type
        $query->join('e.complexType', 't');
        $countQuery->join('e.complexType', 't');

        //geoState
        $query->join('e.geoState', 's');
        $countQuery->join('e.geoState', 's');


        //var_dump($filterComplex);die;

        if ($filterComplex != null) {
            $query->andWhere('e.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
            $countQuery->andWhere('e.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
        }


        // Fields Search
        foreach ($columns as $key => $column) {
            if ($column['search']['value'] != '') {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch ($column['name']) {
                    case 'id':
                        {
                            $searchQuery = 'e.id =' . $searchItem;
                            break;
                        }
                    case 'name':
                        {
                            $searchQuery = 'e.name LIKE \'%' . $searchItem . '%\'';
                            break;
                        }
                    case 'city':
                        {
                            $searchQuery = 's.name LIKE \'%' . $searchItem . '%\'';
                            break;
                        }
                    case 'zipCode':
                        {
                            $searchQuery = 'e.zipCode LIKE \'%' . $searchItem . '%\'';
                            break;
                        }
                    case 'complexType':
                        {
                            if ($businessLocale == "es") {
                                $searchQuery = 't.nameES LIKE \'%' . $searchItem . '%\'';
                            } else {
                                $searchQuery = 't.nameEN LIKE \'%' . $searchItem . '%\'';
                            }

                            break;
                        }


                }


                if ($searchQuery !== null) {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order) {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order) {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '') {
                $orderColumn = null;

                switch ($order['name']) {
                    case 'id':
                        {
                            $orderColumn = 'e.id';
                            break;
                        }
                    case 'name':
                        {
                            $orderColumn = 'e.name';
                            break;
                        }
                    case 'city':
                        {
                            $orderColumn = 's.name';
                            break;
                        }
                    case 'zipCode':
                        {
                            $orderColumn = 'e.code';
                            break;
                        }
                    case 'complexType':
                        {
                            if ($businessLocale == "es") {
                                $orderColumn = 't.nameES';
                            } else {
                                $orderColumn = 't.nameEN';
                            }

                            break;
                        }

                }

                if ($orderColumn !== null) {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" => $results,
            "countResult" => $countResult
        );
    }


    public function getComplexForInvoice($duePaymentDay)
    {

        $sql = "	SELECT  c.id, c.created_at, c.name complex_name, c.due_payment_day,
	                        b.customer_id,
	                        country.id country_id
                    FROM    complex c
                   	    INNER JOIN business b ON (b.id = c.business_id)
                   	    INNER JOIN geo_state s ON (b.geo_state_id = s.id)
                   	    INNER JOIN geo_country country ON (s.geo_country_id = country.id)
                    WHERE   c.enabled = 1
                    AND     DATE_ADD(DATE(c.created_at), INTERVAL 15 DAY) <= DATE(NOW())
                    AND b.customer_id != 0
                    ";
        //el date add +2 es para un mes de prueba gratis
        //AND     DATE_ADD(DATE(c.created_at), INTERVAL 2 MONTH) <= DATE(NOW())

        //print $sql;die;

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();

        //var_dump($execute);die;

        $arrReturn = array();

        foreach($execute as $c){
            //$date = strtotime($c["created_at"]);
            //$createdDay = $this->jjg_calculate_next_month($date);
            //var_dump($createdDay);die;

            //if day is same day send invoice
            //$today = gmdate("d");
            //var_dump($today);die;

            //if($createdDay == $today){
                //PRINT "entraa".$createdDay."==".$today;

                $complexID = $c["id"];
                //var_dump($complexID);die;
                $properties = intval($this->getPropertiesQuantityByComplex($complexID));

                ///get FEE for this complex on the agreement plan
                $myFee = $this->getComplexFee($properties);
                if(intval($myFee) > 0){
                    $arrReturn[$complexID] = array();
                    $arrReturn[$complexID]["country_id"] = intval($c["country_id"]);
                    $arrReturn[$complexID]["fee"] = $myFee;
                    $arrReturn[$complexID]["customer_id"] = $c["customer_id"];
                    $arrReturn[$complexID]["complex_name"] = $c["complex_name"];
                    $arrReturn[$complexID]["properties_quantity"] = $properties;


                }
            //}
        }

        //var_dump($arrReturn);die;
        return $arrReturn;

    }


    public function getComplexFee($quantity){

        $sql = "    SELECT fee
                    FROM	agreement_plan
                    WHERE	{$quantity} >= property_limit_from AND {$quantity} <= property_limit_to";


        //print $sql;die;
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();

        //var_dump($execute);die;

        if(!empty($execute)){
            $myFee = floatval($execute[0]["fee"]);
            return $myFee;
        }
        else{
            return 0;
        }

    }


    public function getPropertiesQuantityByComplex($complexID){

        $sql = "    SELECT COUNT(p.id) quantity
                    FROM	property p
                        INNER JOIN complex_sector s ON (p.complex_sector_id = s.id)
                        INNER JOIN complex c ON (s.complex_id = c.id)
                        AND c.id = {$complexID}
                    WHERE	p.enabled = 1";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();

        if(!empty($execute)){
            return $execute[0]["quantity"];
        }
        else{
            return 1;
        }


    }


    /**
     * Function to calculate the same day one month in the future.
     *
     * This is necessary because some months don't have 29, 30, or 31 days. If the
     * next month doesn't have as many days as this month, the anniversary will be
     * moved up to the last day of the next month.
     *
     * @param $start_date (optional)
     *   UNIX timestamp of the date from which you'd like to start. If not given,
     *   will default to current time.
     *
     * @return $timestamp
     *   UNIX timestamp of the same day or last day of next month.
     */
    public function jjg_calculate_next_month($start_date = FALSE)
    {
        if ($start_date) {
            $now = $start_date; // Use supplied start date.
        } else {
            $now = time(); // Use current time.
        }

        // Get the current month (as integer).
        $current_month = date('n', $now);

        // If the we're in Dec (12), set current month to Jan (1), add 1 to year.
        if ($current_month == 12) {
            $next_month = 1;
            $plus_one_month = mktime(0, 0, 0, 1, date('d', $now), date('Y', $now) + 1);
        } // Otherwise, add a month to the next month and calculate the date.
        else {
            $next_month = $current_month + 1;
            $plus_one_month = mktime(0, 0, 0, date('m', $now) + 1, date('d', $now), date('Y', $now));
        }

        $i = 1;
        // Go back a day at a time until we get the last day next month.
        while (date('n', $plus_one_month) != $next_month) {
            $plus_one_month = mktime(0, 0, 0, date('m', $now) + 1, date('d', $now) - $i, date('Y', $now));
            $i++;
        }

        return gmdate("d", $plus_one_month);

    }



    public function getComplexAdmins($complexID)
    {


        $sql = "	SELECT  u.id, u.username, u.name
                    FROM    user_complex uc
                   	    INNER JOIN user u ON (uc.user_id = u.id)
                    WHERE     uc.complex_id = {$complexID}
                    AND     u.role_id IN (1,2)
                    ";
        //ROLE ID = 2 COMPLEX ADMINISTRATOR
        //ROLE ID = 1 BUSINESS ADMINISTRATOR

        //print $sql;die;

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();

        $arrReturn = array();
        foreach($execute as $u){
            $arrReturn[$u["id"]] = $u["username"];
        }

        return $arrReturn;

    }

}
