<?php

namespace Backend\AdminBundle\Repository;

/**
 * IconRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IconRepository extends \Doctrine\ORM\EntityRepository
{
}
