<?php

namespace Backend\AdminBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ModuleAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleAccessRepository extends \Doctrine\ORM\EntityRepository
{
	
	
	//cleanRoleAccess
	public function cleanRoleAccess($roleID){
		
		$sql = "	DELETE
					FROM 	module_access"; 
					//WHERE 	role_id = '{$roleID}'";
					
		$stmt = $this->getEntityManager()->getConnection()->prepare($sql);
	    $stmt->execute();
		
	    //return $stmt->fetchAll();					
		
	}

	
	public function getUserAccessByRole($roleID){
		

		if(intval($roleID) != 0){

					
			$sql = "	SELECT 	ma.id moduleAccessID, ma.module_id moduleID,
								m.name moduleName,  m.system_name systemName, m.parent_module_id parent, 
								m.system_route systemRoute, m.menu_type menuType, m.menu_order menuOrder,
								m.visible, m.icon, m.translation_label
						FROM 	module_access ma
							INNER JOIN module m ON (ma.module_id = m.id)
							INNER JOIN role r ON (ma.role_id = r.id)
						WHERE 	ma.role_id = '{$roleID}'
						AND     r.enabled = 1
						AND   m.visible = 1
						ORDER BY m.name, m.id";
			            //ORDER BY m.menu_order, m.id
			
		}
		else{
			return null;
		}

					
				
		$stmt = $this->getEntityManager()->getConnection()->prepare($sql);
	    $stmt->execute();
		
	    $execute = $stmt->fetchAll();
		/*
		print "<pre>";
		var_dump($execute);die;
		 * 
		 */
		
		$arrMenu = array();
		
		//var_dump($execute);
		foreach ($execute as $row) {
			//var_dump($row);
			
			
			if($row["menuType"] == "menu"){
				//$arrMenu[$row["moduleID"]] = array();
				$arrMenu[$row["moduleID"]]["moduleName"] = $row["moduleName"];	
				$arrMenu[$row["moduleID"]]["moduleType"] = $row["menuType"];
				$arrMenu[$row["moduleID"]]["visible"] = $row["visible"];
				$arrMenu[$row["moduleID"]]["icon"] = $row["icon"];
                $arrMenu[$row["moduleID"]]["translation_label"] = $row["translation_label"];
			}
			elseif($row["menuType"] == "link"){
				$arrMenu[$row["moduleID"]]["moduleName"] = $row["moduleName"];
				$arrMenu[$row["moduleID"]]["systemName"] = $row["systemName"];
				$arrMenu[$row["moduleID"]]["systemRoute"] = $row["systemRoute"];
				$arrMenu[$row["moduleID"]]["moduleType"] = $row["menuType"];
				$arrMenu[$row["moduleID"]]["visible"] = $row["visible"];
				$arrMenu[$row["moduleID"]]["icon"] = $row["icon"];
                $arrMenu[$row["moduleID"]]["translation_label"] = $row["translation_label"];
			}
			else{
				$arrMenu[$row["parent"]][$row["moduleID"]]["moduleName"] = $row["moduleName"];
				$arrMenu[$row["parent"]][$row["moduleID"]]["systemName"] = $row["systemName"];
				$arrMenu[$row["parent"]][$row["moduleID"]]["systemRoute"] = $row["systemRoute"];
				$arrMenu[$row["parent"]][$row["moduleID"]]["moduleType"] = $row["menuType"];
				$arrMenu[$row["parent"]][$row["moduleID"]]["visible"] = $row["visible"];
                $arrMenu[$row["parent"]][$row["moduleID"]]["translation_label"] = $row["translation_label"];
				
			}



			
		}					
		
		/*
		print "<pre>";
		var_dump($arrMenu);die;
		 * 
		 */
		
		return $arrMenu;
	}


	public function getModules(){
		

		$sql = "	SELECT 	m.id moduleID, m.name moduleName, m.translation_label, m.system_name systemName, m.parent_module_id parent, 
							m.system_route systemRoute, m.menu_type menuType, m.menu_order menuOrder, m.icon 
					FROM	module m
					WHERE   m.visible = 1
					ORDER BY m.name, m.id";
				
		$stmt = $this->getEntityManager()->getConnection()->prepare($sql);
	    $stmt->execute();
		
	    $execute = $stmt->fetchAll();
		
		/*		
		print "<pre>";
		var_dump($execute);die;
		 * */
		
		$arrMenu = array();
		
		
		foreach ($execute as $row) {
			//var_dump($row);
			
			
			if($row["menuType"] == "menu"){
				//$arrMenu[$row["moduleID"]] = array();
				$arrMenu[$row["moduleID"]]["moduleName"] = $row["moduleName"];	
				$arrMenu[$row["moduleID"]]["moduleType"] = $row["menuType"];
				$arrMenu[$row["moduleID"]]["moduleID"] = $row["moduleID"];
				$arrMenu[$row["moduleID"]]["parent"] = $row["parent"];
				$arrMenu[$row["moduleID"]]["icon"] = $row["icon"];
                $arrMenu[$row["moduleID"]]["translation_label"] = $row["translation_label"];
			}
			elseif($row["menuType"] == "link"){
				$arrMenu[$row["moduleID"]]["moduleName"] = $row["moduleName"];
				$arrMenu[$row["moduleID"]]["systemName"] = $row["systemName"];
				$arrMenu[$row["moduleID"]]["systemRoute"] = $row["systemRoute"];
				$arrMenu[$row["moduleID"]]["moduleType"] = $row["menuType"];
				$arrMenu[$row["moduleID"]]["moduleID"] = $row["moduleID"];
				$arrMenu[$row["moduleID"]]["parent"] = $row["parent"];
				$arrMenu[$row["moduleID"]]["icon"] = $row["icon"];
                $arrMenu[$row["moduleID"]]["translation_label"] = $row["translation_label"];
			}
			else{
				$arrMenu[$row["parent"]][$row["moduleID"]]["moduleName"] = $row["moduleName"];
				$arrMenu[$row["parent"]][$row["moduleID"]]["systemName"] = $row["systemName"];
				$arrMenu[$row["parent"]][$row["moduleID"]]["systemRoute"] = $row["systemRoute"];
				$arrMenu[$row["parent"]][$row["moduleID"]]["moduleType"] = $row["menuType"];
				$arrMenu[$row["parent"]][$row["moduleID"]]["moduleID"] = $row["moduleID"];
				$arrMenu[$row["parent"]][$row["moduleID"]]["parent"] = $row["parent"];
                $arrMenu[$row["parent"]][$row["moduleID"]]["translation_label"] = $row["translation_label"];
			}	

			
		}					
		
		/*
		print "<pre>";
		var_dump($arrMenu);die;
		 * 
		 */
		
		return $arrMenu;
	}


	
		
	
	
}
