<?php

namespace Backend\AdminBundle\Repository;

/**
 * PaymentLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentLogRepository extends \Doctrine\ORM\EntityRepository
{
}
