<?php

namespace Backend\AdminBundle\Repository;

/**
 * PollTenantAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollTenantAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
