<?php

namespace Backend\AdminBundle\Repository;

/**
 * PollQuestionOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollQuestionOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
