<?php

namespace Backend\AdminBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * PollQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollQuestionRepository extends \Doctrine\ORM\EntityRepository
{
    private function getApiPoll($pollId)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a, p, pqt')
            ->leftJoin('a.poll', 'p', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('p', 'a.poll'),
                $qb->expr()->eq('p.enabled', '1')
            ))
            ->leftJoin('a.pollQuestionType', 'pqt', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('pqt', 'a.pollQuestionType'),
                $qb->expr()->eq('pqt.enabled', '1')
            ))
            ->where('a.enabled = 1')
            ->andWhere('p.id = :poll_id')
            ->setParameter('poll_id', $pollId)
        ;

        return $qb->getQuery()->getResult();
    }
}
