<?php

namespace Backend\AdminBundle\Repository;

/**
 * PollQuestionOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollQuestionOptionRepository extends \Doctrine\ORM\EntityRepository
{

    private function getApiPoll($ids)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a, p')
            ->innerJoin('a.poll', 'p')
            ->where('a.enabled = 1');

        if (count($ids) > 0) {
            $qb->andWhere($qb->expr()->in('t.id', $ids));
        }

        return $qb->getQuery()->getResult();
    }

}
