<?php

namespace Backend\AdminBundle\Repository;

/**
 * PropertyContractTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyContractTransactionRepository extends \Doctrine\ORM\EntityRepository
{




    public function getApiPayments($propertyID, $month, $year)
    {

        $dateStart = $year."-".$month."-"."01 00:00:00";
        $dateEnd = $year."-".$month."-"."31 23:59:59";

        $query = $this->createQueryBuilder('e');



        // Create inner joins
        //complex
        //$query->join('e.complex', 'c');
        //transactionType
        $query->join('e.propertyTransactionType', 'tt');
        //property Contract
        $query->join('e.propertyContract', 'pc');
        //property
        $query->join('pc.property', 'p');

        $query->andWhere('p.id = :prop_id')
        ->setParameter('prop_id', $propertyID)

        ->andWhere('e.dueDate >= :myDateStart AND e.dueDate <= :myDateEnd')
        ->setParameter('myDateStart', date("Y-m-d H:i:s", strtotime($dateStart)))
        ->setParameter('myDateEnd', date("Y-m-d H:i:s", strtotime($dateEnd)));

        //ENABLED
        $query->andWhere("e.enabled = 1");
        //filter just active contracts
        $query->andWhere("pc.isActive = 1");
        $query->andWhere("pc.enabled = 1");

        $query->orderBy('e.createdAt', 'DESC');

        return $query->getQuery()->getResult();
    }






    //getRequiredDTData($start, $length, $orders, $search, $columns, $filterComplex, null, $this->translator->getLocale());

    public function getRequiredDTData($start, $length, $orders, $search, $columns, $filterComplex, $locale, $filterProperty = null )
    {
        //print "entra";die;
        // Create Main Query
        $query = $this->createQueryBuilder('e');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        //ENABLED
        $query->andWhere("e.enabled = 1");
        $countQuery->andWhere("e.enabled = 1");

        // Create inner joins
        //complex
        $query->join('e.complex', 'c');
        $countQuery->join('e.complex', 'c');

        //transactionType
        $query->join('e.propertyTransactionType', 'tt');
        $countQuery->join('e.propertyTransactionType', 'tt');

        //property Contract
        $query->join('e.propertyContract', 'pc');
        $countQuery->join('e.propertyContract', 'pc');

        //property
        $query->join('pc.property', 'p');
        $countQuery->join('pc.property', 'p');


        if ($filterComplex != null) {
            $query->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
            $countQuery->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
        }

        if($filterProperty != null){
            $query->andWhere('p.id = :propertyID')->setParameter('propertyID', $filterProperty);
            $countQuery->andWhere('p.id = :propertyID')->setParameter('propertyID', $filterProperty);
        }



        // Fields Search
        foreach ($columns as $key => $column) {
            if ($column['search']['value'] != '') {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch ($column['name']) {
                    case 'id':
                        {
                            $searchQuery = 'e.id =' . $searchItem;
                            break;
                        }
                    case 'description':
                        {
                            $searchQuery = 'e.description LIKE \'%' . $searchItem . '%\'';
                            break;
                        }

                    case 'property':
                        {
                            $searchQuery = 'p.propertyNumber LIKE \'%' . $searchItem . '%\'';
                            break;
                        }

                    case 'type':
                        {

                            if($locale == "en"){
                                $searchQuery = 'tt.nameEN LIKE \'%' . $searchItem . '%\'';
                            }
                            else{
                                $searchQuery = 'tt.nameES LIKE \'%' . $searchItem . '%\'';
                            }

                            break;
                        }


                    case 'createdat':
                        {
                            $searchQuery = 'e.createdAt LIKE \'%' . $searchItem . '%\'';
                            break;
                        }

                    case 'duedate':
                    {
                        $searchQuery = 'e.dueDate LIKE \'%' . $searchItem . '%\'';
                        break;
                    }
                    case 'paid':
                        {
                            $searchQuery = 'e.paidDate LIKE \'%' . $searchItem . '%\'';
                            break;
                        }

                }


                if ($searchQuery !== null) {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order) {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order) {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '') {
                $orderColumn = null;

                switch ($order['name']) {
                    case 'id':
                        {
                            $orderColumn = 'e.id';
                            break;
                        }
                    case 'description':
                        {
                            $orderColumn = 'e.description';
                            break;
                        }
                    case 'property':
                        {
                            $orderColumn = 'p.property_number';
                            break;
                        }

                    case 'type':
                        {
                            $orderColumn = 'tt.nameEN';
                            break;
                        }
                    case 'status':
                        {
                            $orderColumn = 'e.status';
                            break;
                        }
                    case 'createdat':
                        {
                            $orderColumn = 'e.createdAt';
                            break;
                        }
                    case 'duedate':
                    {
                        $orderColumn = 'e.dueDate';
                        break;
                    }
                    case 'paid':
                        {
                            $orderColumn = 'e.paidDate';
                            break;
                        }

                }

                if ($orderColumn !== null) {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" => $results,
            "countResult" => $countResult
        );
    }

}
