<?php

namespace Backend\AdminBundle\Repository;

/**
 * PropertyPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
