<?php

namespace Backend\AdminBundle\Repository;

/**
 * PropertyContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyContractRepository extends \Doctrine\ORM\EntityRepository
{
}
