<?php

namespace Backend\AdminBundle\Repository;

/**
 * PropertyContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyContractRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApiWelcomePrivateKey($property)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a, p')
            ->innerJoin('a.property', 'p')
            ->where('a.enabled = 1')
            ->andWhere('p.enabled = 1')
            ->andWhere('p.id = :property_id')
            ->andWhere('a.isActive = 1')
            ->setParameter('property_id', $property->getId())
            ->orderBy('a.createdAt', 'DESC');

        return $qb->getQuery()->getResult();
    }


    //getRequiredDTData($start, $length, $orders, $search, $columns, $filters);
    public function getRequiredDTData($start, $length, $orders, $search, $columns, $filterComplex)
    {
        //print "entra";die;
        // Create Main Query
        $query = $this->createQueryBuilder('e');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        //ENABLED
        $query->andWhere("e.enabled = 1");
        $countQuery->andWhere("e.enabled = 1");

        // Create inner joins


        //property
        $query->join('e.property', 'p');
        $countQuery->join('e.property', 'p');

        //sector
        $query->join('p.complexSector', 's');
        $countQuery->join('p.complexSector', 's');



        //complex
        $query->join('s.complex', 'c');
        $countQuery->join('s.complex', 'c');

        if($filterComplex != null){
            $query->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
            $countQuery->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
        }

        //owner // property_owner_id
        //$query->leftJoin('e.owner', 'o');
        //$countQuery->leftJoin('e.owner', 'o');



        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                        {
                            $searchQuery = 'e.id ='. $searchItem;
                            break;
                        }

                    case 'complex':
                        {
                            $searchQuery = 'c.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'sector':
                        {
                            $searchQuery = 's.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                    case 'property':
                        {
                            $searchQuery = 'p.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                    case 'active':
                        {
                            if($searchItem == "Yes" || $searchItem == "Si"){
                                $searchQuery = 'e.isActive = 1';
                            }

                            if($searchItem == "No"){
                                $searchQuery = 'e.isActive = 0';
                            }

                            break;
                        }
                    case 'price':
                        {
                            $searchQuery = 'e.rentalPrice LIKE \'%'.$searchItem.'%\'';
                            break;
                        }


                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                        {
                            $orderColumn = 'e.id';
                            break;
                        }
                    case 'complex':
                        {
                            $orderColumn = 'c.name';
                            break;
                        }

                    case 'sector':
                        {
                            $orderColumn = 's.name';
                            break;
                        }

                    case 'active':
                        {
                            $orderColumn = 'e.isActive';
                            break;
                        }
                    case 'property':
                        {
                            $orderColumn = 'p.name';
                            break;
                        }
                    case 'active':
                        {
                            $orderColumn = 'e.isActive';
                            break;
                        }

                    case 'price':
                        {
                            $orderColumn = 'e.rentalPrice';
                            break;
                        }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }


    public function disableContracts($activeContractID, $propertyID){

        $sql = "	UPDATE  property_contract
					SET	    is_active = 0
					WHERE   id != {$activeContractID}
					AND     property_id = {$propertyID}
					AND     property_transaction_type_id = 3";
        //WHERE 	role_id = '{$roleID}'";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

    }


}
