<?php

namespace Backend\AdminBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApiPostFaq($propertyId) {
        $qb = $this->createQueryBuilder('a');

        $qb->select('b.id as id')
            ->innerJoin('a.complex', 'c')
            ->innerJoin('c.business', 'b')
            ->where('a.enabled = 1')
            ->andWhere('b.enabled = 1')
            ->andWhere('c.enabled = 1')
            ->andWhere('a.id = :property_id')
            ->setParameter('property_id', $propertyId)
        ;

        return $qb->getQuery()->getArrayResult();
    }

    public function getApiCommonAreas($propertyId)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a, c')
            ->innerJoin('a.complex', 'c')
            ->where('a.enabled = 1')
            ->andWhere('c.enabled = 1')
            ->andWhere('a.id = :property_id')
            ->setParameter('property_id', $propertyId)
            ->orderBy('a.createdAt', 'ASC');

        return $qb->getQuery()->getResult();
    }



    public function getGenericApiProperty()
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a, s, p')
            ->leftJoin('a.complexSector', 's', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('s', 'a.complexSector'),
                $qb->expr()->eq('s.enabled', '1')
            ))
            ->leftJoin('a.propertyType', 'p', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('p', 'a.propertyType'),
                $qb->expr()->eq('p.enabled', '1')
            ))
            ->where('a.enabled = 1')

            ->orderBy('a.createdAt', 'ASC')
            ;
        return $qb;
    }


    public function getApiProperty($code)
    {
        $qb = $this->getGenericApiProperty();

        $qb->andWhere('a.code = :code')
            ->setParameter('code', $code);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getApiPropertyDetail($id, $user)
    {
        $qb = $this->getGenericApiProperty();

        //$qb->andWhere('a.owner = :user')
        $qb->andWhere('a.id = :pid')
            //->setParameter('user', $user)
            ->setParameter('pid', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }


    /*
    public function getApiProperties($user)
    {
        $qb = $this->getGenericApiProperty();

        $qb->andWhere('a.owner = :user')
            ->setParameter('user', $user);

        return $qb->getQuery()->getResult();
    }

    public function countApiProperties($user)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('count(a.id)')
            ->where('a.enabled = 1');
            //->andWhere('a.owner = :user')
            //->setParameter('user', $user);

        return $qb->getQuery()->getSingleScalarResult();
    }
    */


    //getRequiredDTData($start, $length, $orders, $search, $columns, $filters);
    public function getRequiredDTData($start, $length, $orders, $search, $columns, $filterComplex)
    {
        //print "entra";die;
        // Create Main Query
        $query = $this->createQueryBuilder('e');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        //ENABLED
        $query->andWhere("e.enabled = 1");
        $countQuery->andWhere("e.enabled = 1");

        // Create inner joins

        //sector
        $query->join('e.complexSector', 's');
        $countQuery->join('e.complexSector', 's');


        //complex
        $query->join('s.complex', 'c');
        $countQuery->join('s.complex', 'c');



        if ($filterComplex != null) {
            $query->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
            $countQuery->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
        }

        //owner
        //$query->leftJoin('e.owner', 'o');
        //$countQuery->leftJoin('e.owner', 'o');

        //main tenant
        $query->leftJoin('e.mainTenant', 't');
        $countQuery->leftJoin('e.mainTenant', 't');


        // Fields Search
        foreach ($columns as $key => $column) {
            if ($column['search']['value'] != '') {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch ($column['name']) {
                    case 'id':
                        {
                            $searchQuery = 'e.id =' . $searchItem;
                            break;
                        }
                    case 'number':
                        {
                            $searchQuery = 'e.propertyNumber LIKE \'%' . $searchItem . '%\'';
                            break;
                        }
                        /*
                    case 'code':
                        {
                            $searchQuery = 'e.code LIKE \'%' . $searchItem . '%\'';
                            break;
                        }
                        */

                    case 'complex':
                        {
                            $searchQuery = 'c.name LIKE \'%' . $searchItem . '%\'';
                            break;
                        }
                    case 'sector':
                        {
                            $searchQuery = 's.name LIKE \'%' . $searchItem . '%\'';
                            break;
                        }

                    case 'owner':
                        {
                            $searchQuery = 'e.ownerEmail LIKE \'%' . $searchItem . '%\'';
                            break;
                        }

                    case 'tenant':
                        {
                            $searchQuery = 't.email LIKE \'%' . $searchItem . '%\'';
                            break;
                        }


                }


                if ($searchQuery !== null) {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order) {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order) {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '') {
                $orderColumn = null;

                switch ($order['name']) {
                    case 'id':
                        {
                            $orderColumn = 'e.id';
                            break;
                        }
                    case 'number':
                        {
                            $orderColumn = 'e.propertyNumber';
                            break;
                        }
                        /*
                    case 'code':
                        {
                            $orderColumn = 'e.code';
                            break;
                        }
                        */
                    case 'sector':
                        {
                            $orderColumn = 's.name';
                            break;
                        }

                    case 'owner':
                        {
                            $orderColumn = 'e.ownerEmail';
                            break;
                        }

                    case 'tenant':
                        {
                            $orderColumn = 't.email';
                            break;
                        }

                }

                if ($orderColumn !== null) {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" => $results,
            "countResult" => $countResult
        );
    }

    public function getCountByComplex($complexID){


        $qb = $this->createQueryBuilder('s');
        $qb->select('count(s.id)');
        //$qb->from('BackendAdminBundle:ComplexSector','s');
        $qb->andWhere('s.complex = :complexid');
        $qb->setParameter('complexid', $complexID);

        $count = $qb->getQuery()->getSingleScalarResult();

        return intval($count);
    }



    public function getPropertiesWithContract($sectorID){


        $sql = "	SELECT 	DISTINCT(p.id), p.property_number
                    FROM 	property p
                        INNER JOIN property_contract pc ON (pc.property_id = p.id)
                        INNER JOIN tenant_contract tc ON (tc.property_contract_id = pc.id)
                    WHERE 	p.complex_sector_id = {$sectorID}
                    AND     pc.enabled = 1
                    AND     pc.is_active = 1
                    
                    ORDER BY p.property_number ASC
                    ";
                    //AND     tc.enabled = 1

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();

        return $execute;
    }



    public function getPropertyLog($propertyID, $locale){

        //LOG COLUMNS
        // date, description, user, status



        //TICKETS
        $sqlTickets = "	    SELECT 	tlog.created_at createddate, u.name username, 
	                                t.id ticket_id, ts.name_es status_es, ts.name_en status_en
                            FROM 	property p
                                INNER JOIN ticket t ON (t.property_id =  p.id)
                                INNER JOIN ticket_status_log tlog ON (tlog.ticket_id = t.id)
                                INNER JOIN ticket_status ts ON (ts.id = tlog.ticket_status_id)
                                INNER JOIN user u ON (tlog.created_by = u.id)
                            WHERE  p.id = {$propertyID}
                            AND    t.ticket_type_id = 1
                            ORDER BY tlog.created_at DESC
                            LIMIT 100     
                            ";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sqlTickets);
        $stmt->execute();

        $executeTickets = $stmt->fetchAll();

        $tempArray = array();
        $arrOrder = array();

        $index = 0;

        foreach($executeTickets as $key => $value ){

            $createdAt = $value["createddate"];
            $unixtime = strtotime($createdAt);

            $arrOrder[$index] = $unixtime;

            $tempArray[$index] = array();
            $tempArray[$index]["date"] = $createdAt;
            $tempArray[$index]["description"] = "Ticket #".$value["ticket_id"];
            $tempArray[$index]["user"] = $value["username"];
            $tempArray[$index]["status"] = $locale == "en" ? $value["status_en"] : $value["status_es"];

            $index++;
        }


        //PAYMENTS
        $sqlPayments = "SELECT 	plog.created_at createddate, u.name username, plog.status, plog.payment_amount, 
                                t.description, t.id payment_id, 
                                ttype.name_es, ttype.name_en, 
                                carea.name common_area
                        FROM	property_contract_transaction t
                            INNER JOIN payment_log plog ON (plog.property_contract_transaction_id = t.id)
                            INNER JOIN property_transaction_type ttype ON (ttype.id = t.property_transaction_type_id)
                            INNER JOIN property_contract contract ON (contract.id = t.property_contract_id)
                            INNER JOIN property p ON (p.id = contract.property_id)
                            LEFT JOIN  common_area_reservation reservation ON (reservation.id = t.common_area_reservation_id)
                            LEFT JOIN  common_area carea ON (carea.id = reservation.common_area_id)
                            INNER JOIN user u ON (plog.created_by = u.id)
                        WHERE	p.id = {$propertyID}
                        ORDER BY plog.created_at DESC  
                        LIMIT 100      
                        ";


        $stmt = $this->getEntityManager()->getConnection()->prepare($sqlPayments);
        $stmt->execute();

        $executePayments = $stmt->fetchAll();

        foreach($executePayments as $key => $value ){

            $createdAt = $value["createddate"];
            $unixtime = strtotime($createdAt);

            $arrOrder[$index] = $unixtime;

            $tempArray[$index] = array();
            $tempArray[$index]["date"] = $createdAt;

            $payment = $locale == "en" ? "Payment" : "Pago";
            $commonArea = $value["common_area"] != NULL ? $value["common_area"] : '';
            $tempArray[$index]["description"] = $commonArea." {$payment} #".$value["payment_id"].": $".number_format($value["payment_amount"], 2, ".",'');
            $tempArray[$index]["user"] = $value["username"];
            $tempArray[$index]["status"] = $value["status"];

            $index++;
        }


        ///BOOKING
        $sqlBooking = "SELECT 	blog.created_at createddate, u.name username, blog.status, 
                                carea.name common_area,
                                car.id
                        FROM    booking_log blog 
                            INNER JOIN common_area_reservation car ON (blog.common_area_reservation_id = car.id)
                            
                            INNER JOIN  common_area carea ON (carea.id = car.common_area_id)
                            INNER JOIN user u ON (blog.created_by = u.id)
                            INNER JOIN property p ON (p.id = car.property_id)
                        WHERE	p.id = {$propertyID}
                        ORDER BY blog.created_at DESC  
                        LIMIT 100      
                        ";
        //INNER JOIN common_area_reservation_status rstatus ON (rstatus.id = car.common_area_reservation_status_id)


        $stmt = $this->getEntityManager()->getConnection()->prepare($sqlBooking);
        $stmt->execute();

        $executeBooking = $stmt->fetchAll();

        foreach($executeBooking as $key => $value ){

            $createdAt = $value["createddate"];
            $unixtime = strtotime($createdAt);

            $arrOrder[$index] = $unixtime;

            $tempArray[$index] = array();
            $tempArray[$index]["date"] = $createdAt;


            $reservation = $locale == "en" ? "Booking" : "Reservación";
            $commonArea = $value["common_area"];
            $tempArray[$index]["description"] = $reservation ."#".$value["id"].": ".$commonArea;

            $tempArray[$index]["user"] = $value["username"];
            $tempArray[$index]["status"] = $value["status"];

            $index++;
        }

        //arsort() - sort associative arrays in descending order, according to the value.

        arsort($arrOrder);
        //var_dump($arrOrder);die;
        $arrReturn = array();

        foreach ($arrOrder as $key => $value){

            $arrReturn[] = $tempArray[$key];

        }

        return $arrReturn;

    }



    public function getStats($complexID){

        $arrReturn = array();

        $countProperties = "    SELECT  COUNT(p.id) quantity
                                FROM 	property p
                                WHERE   p.enabled = 1
                                AND     p.complex_id = {$complexID}";
        //AND     t.complex_id = {$complexID}

        $stmt = $this->getEntityManager()->getConnection()->prepare($countProperties);
        $stmt->execute();
        $execute = $stmt->fetchAll();

        $arrReturn["total"] = $execute[0]["quantity"];

        $countPropertiesRented = "    SELECT  COUNT(p.id) quantity
                                        FROM 	property p    
                                        WHERE   p.enabled = 1
                                        AND     p.complex_id = {$complexID}
                                        AND     p.is_available = 0";
        //AND     t.complex_id = {$complexID}

        $stmt = $this->getEntityManager()->getConnection()->prepare($countPropertiesRented);
        $stmt->execute();
        $execute = $stmt->fetchAll();

        $arrReturn["rented"] = $execute[0]["quantity"];
        $arrReturn["empty"] = $arrReturn["total"] - $arrReturn["rented"];

        return $arrReturn;

    }

}
