<?php

namespace Backend\AdminBundle\Repository;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApiCommonAreas($propertyId)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a, cs, c, o')
            ->innerJoin('a.complexSector', 's')
            ->innerJoin('s.complex', 'c')
            ->leftJoin('a.owner', 'o')
            ->where('a.enabled = 1')
            ->andWhere('cs.enabled = 1')
            ->andWhere('c.enabled = 1')
            ->andWhere('o.enabled = 1')
            ->andWhere('a.id = :property_id')
            ->setParameter('property_id', $propertyId)
            ->orderBy('a.createdAt', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function getApiProperty($code, $user)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a, s.id, p.id')
            ->leftJoin('a.complexSector', 's')
            ->leftJoin('a.propertyType', 'p')
            ->where('a.enabled = 1')
            ->andWhere('s.enabled = 1')
            ->andWhere('p.enabled = 1')
            ->andWhere('a.code = :code')
            ->andWhere('a.owner = :user')
            ->setParameter('code', $code)
            ->setParameter('user', $user)
            ->orderBy('a.createdAt', 'ASC');

        return $qb->getQuery()->getSingleResult();
    }

    public function countApiProperties($user)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('count(a.id)')
            ->where('a.enabled = 1')
            ->andWhere('a.owner = :user')
            ->setParameter('user', $user);

        return $qb->getQuery()->getSingleScalarResult();
    }


    //getRequiredDTData($start, $length, $orders, $search, $columns, $filters);
    public function getRequiredDTData($start, $length, $orders, $search, $columns, $filterComplex)
    {
        //print "entra";die;
        // Create Main Query
        $query = $this->createQueryBuilder('e');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        //ENABLED
        $query->andWhere("e.enabled = 1");
        $countQuery->andWhere("e.enabled = 1");


        // Create inner joins

        //sector
        $query->join('e.complexSector', 's');
        $countQuery->join('e.complexSector', 's');


        //complex
        $query->join('s.complex', 'c');
        $countQuery->join('s.complex', 'c');

        if ($filterComplex != null) {
            $query->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
            $countQuery->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
        }

        //owner
        $query->leftJoin('e.owner', 'o');
        $countQuery->leftJoin('e.owner', 'o');

        //main tenant
        $query->leftJoin('e.mainTenant', 't');
        $countQuery->leftJoin('e.mainTenant', 't');


        // Fields Search
        foreach ($columns as $key => $column) {
            if ($column['search']['value'] != '') {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch ($column['name']) {
                    case 'id':
                        {
                            $searchQuery = 'e.id =' . $searchItem;
                            break;
                        }
                    case 'name':
                        {
                            $searchQuery = 'e.name LIKE \'%' . $searchItem . '%\'';
                            break;
                        }
                    case 'code':
                        {
                            $searchQuery = 'e.code LIKE \'%' . $searchItem . '%\'';
                            break;
                        }

                    case 'complex':
                        {
                            $searchQuery = 'c.name LIKE \'%' . $searchItem . '%\'';
                            break;
                        }
                    case 'sector':
                        {
                            $searchQuery = 's.name LIKE \'%' . $searchItem . '%\'';
                            break;
                        }
                    case 'owner':
                        {
                            $searchQuery = 'o.name LIKE \'%' . $searchItem . '%\'';
                            break;
                        }
                    case 'tenant':
                        {
                            $searchQuery = 't.name LIKE \'%' . $searchItem . '%\'';
                            break;
                        }


                }


                if ($searchQuery !== null) {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order) {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order) {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '') {
                $orderColumn = null;

                switch ($order['name']) {
                    case 'id':
                        {
                            $orderColumn = 'e.id';
                            break;
                        }
                    case 'name':
                        {
                            $orderColumn = 'e.name';
                            break;
                        }
                    case 'code':
                        {
                            $orderColumn = 'e.code';
                            break;
                        }
                    case 'sector':
                        {
                            $orderColumn = 's.name';
                            break;
                        }
                    case 'owner':
                        {
                            $orderColumn = 'o.name';
                            break;
                        }
                    case 'tenant':
                        {
                            $orderColumn = 't.name';
                            break;
                        }

                }

                if ($orderColumn !== null) {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" => $results,
            "countResult" => $countResult
        );
    }
}
