<?php

namespace Backend\AdminBundle\Repository;

/**
 * PropertyContractTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyContractTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
