<?php

namespace Backend\AdminBundle\Repository;

/**
 * ShiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftRepository extends \Doctrine\ORM\EntityRepository
{
    
     public function getRequiredDTData($start, $length, $orders, $search, $columns, $otherConditions, $filterComplex)
    {
        //print "entra";die;
        // Create Main Query
        $query = $this->createQueryBuilder('e');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        // Create inner joins
        $query->join('e.complex', 'c');
        $countQuery->join('e.complex', 'c');


        //ENABLED
        $query->andWhere("e.enabled = 1");
        $countQuery->andWhere("e.enabled = 1");

        $query->andWhere("c.enabled = 1");
        $countQuery->andWhere("c.enabled = 1");


        if($filterComplex != null){
            $query->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
            $countQuery->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
        }
        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                        {
                            $searchQuery = 'e.id ='. $searchItem;
                            break;
                        }
                    case 'hourFrom':
                        {
                            $searchQuery = 'e.hourFrom LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'hourTo':
                        {
                            $searchQuery = 'e.hourTo LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'weekDay':
                        {
                            $searchQuery = 'e.weekDay LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'shiftDate':
                        {
                            $searchQuery = 'e.shiftDate LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'overtime':
                        {
                            $searchQuery = 'e.overtime LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'flexibleHours':
                        {
                            $searchQuery = 'e.flexibleHours LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'flexitour':
                        {
                            $searchQuery = 'e.flexitour LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'complex':
                        {
                            $searchQuery = 'c.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }


                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                        {
                            $orderColumn = 'e.id';
                            break;
                        }
                    case 'hourFrom':
                        {
                            $orderColumn = 'e.hourFrom';
                            break;
                        }
                    case 'hourTo':
                        {
                            $orderColumn = 'e.hourTo';
                            break;
                        }
                    case 'weekDay':
                        {
                           $orderColumn = 'e.weekDay';
                            break;
                        }
                    case 'shiftDate':
                        {
                            $orderColumn = 'e.shiftDate';
                            break;
                        }
                    case 'overtime':
                        {
                            $orderColumn = 'e.overtime';
                            break;
                        }
                    case 'flexibleHours':
                        {
                            $orderColumn = 'e.flexibleHours';
                            break;
                        }
                    case 'flexitour':
                        {
                           $orderColumn = 'e.flexitour';
                            break;
                        }
                   
                    case 'complex':
                        {
                            $orderColumn = 'c.name';
                            break;
                        }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }




    public function  clearShiftSchedule($commonAreaID){

        $sql = "	DELETE
					FROM 	shift;
                    WHERE 	common_area_id = {$commonAreaID}";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

    }


    public function getSchedule($commonAreaID)
    {

        $sql = "	SELECT  shift.*,
	                        u.username
					FROM 	shift
					    INNER JOIN user u ON (shift.assigned_to = u.id)
                    WHERE 	complex_id = {$commonAreaID}
                    ORDER BY weekday_single, id";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        //print $sql;die;

        $execute = $stmt->fetchAll();


        if (empty($execute)) {
            return "";
        }



        //$('#schedule').jqs('import', [{ day: 0, periods: [['06:00','07:00']]},{ day: 1, periods: [['06:00','07:00']]},{ day: 2, periods: [['06:00','07:00']]},{ day: 3, periods: [['06:00','07:00']]},{ day: 4, periods: [['06:00','07:00']]},{ day: 5, periods: [['06:00','07:00']]},{ day: 6, periods: [['06:00','07:00']]}]);


        $days = "";


        $arrDays = array();
        foreach ($execute as $row) {

            $day = $row["weekday_single"];

            if (!isset($arrDays[$day])) {

                if ($day > 0 && ($days != "") ) {
                    //$days .= "},";
                    $days .= "]},";
                }

                $arrDays[$day] = $day;
                $days .= "{ day: " . $day . ",";
                $days .= " periods: [";
            }

            //$days .= "['" . $row["hour_from"] . "','" . $row["hour_to"] . "'],";
            $days .= "{start: '".$row["hour_from"]."', end: '".$row["hour_to"]."', title: '".$row["username"]."'},";

        }

        $days = "[" . $days . "]}]";

        //print $days;die;

        return $days;
    }

    public function getUsertoAssignTicket($timezone, $complexID){

        $em  = $this->getEntityManager();

        $timezone =  intval($timezone);

        $myCreationTime = gmdate("Y-m-d H:i:s", time() + 3600*($timezone+date("I")));
        $myTime = gmdate("H:i", time() + 3600*($timezone+date("I")));
        $weekDay = date('w', strtotime($myCreationTime));
        $arrWeekDays = array(0 => 6, 1 => 0, 2 => 1, 3 => 2, 4 => 3, 5 => 4, 6 => 5);
        $weekDaySingle = $arrWeekDays[$weekDay];


        $sql = "	SELECT  assigned_to 
                    FROM    shift
                    WHERE   weekday_single = {$weekDaySingle}
                    AND     complex_id = {$complexID}
                    AND     (hour_from <= '{$myTime}' AND hour_to >= '{$myTime}')
                    LIMIT 1";

        //var_dump($sql);
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();
        if(isset($execute[0])){
            $user = $em->getRepository('BackendAdminBundle:User')->find($execute[0]["assigned_to"]);

        }
        else{
            $complex = $em->getRepository('BackendAdminBundle:Complex')->find($complexID);
            $business = $complex->getBusiness();

            //search for a supervisor or business admin
            //supervisor
            $user = $em->getRepository('BackendAdminBundle:User')->findOneBy(array("role" => 3, "business" => $business->getId()));
            if(!$user){
                //business admin
                $user = $em->getRepository('BackendAdminBundle:User')->findOneBy(array("role" => 1, "business" => $business->getId()));
            }

        }

        return $user;

    }


}
