<?php

namespace Backend\AdminBundle\Repository;

/**
 * ShiftUserConmplexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftUserConmplexRepository extends \Doctrine\ORM\EntityRepository
{
}
