<?php

namespace Backend\AdminBundle\Repository;

/**
 * ShiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftRepository extends \Doctrine\ORM\EntityRepository
{
    
     public function getRequiredDTData($start, $length, $orders, $search, $columns, $otherConditions, $filterComplex)
    {
        //print "entra";die;
        // Create Main Query
        $query = $this->createQueryBuilder('e');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        // Create inner joins
        $query->join('e.complex', 'c');
        $countQuery->join('e.complex', 'c');


        //ENABLED
        $query->andWhere("e.enabled = 1");
        $countQuery->andWhere("e.enabled = 1");

        $query->andWhere("c.enabled = 1");
        $countQuery->andWhere("c.enabled = 1");


        if($filterComplex != null){
            $query->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
            $countQuery->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
        }
        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                        {
                            $searchQuery = 'e.id ='. $searchItem;
                            break;
                        }
                    case 'hourFrom':
                        {
                            $searchQuery = 'e.hourFrom LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'hourTo':
                        {
                            $searchQuery = 'e.hourTo LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'weekDay':
                        {
                            $searchQuery = 'e.weekDay LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'shiftDate':
                        {
                            $searchQuery = 'e.shiftDate LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'overtime':
                        {
                            $searchQuery = 'e.overtime LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'flexibleHours':
                        {
                            $searchQuery = 'e.flexibleHours LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'flexitour':
                        {
                            $searchQuery = 'e.flexitour LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'complex':
                        {
                            $searchQuery = 'c.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }


                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                        {
                            $orderColumn = 'e.id';
                            break;
                        }
                    case 'hourFrom':
                        {
                            $orderColumn = 'e.hourFrom';
                            break;
                        }
                    case 'hourTo':
                        {
                            $orderColumn = 'e.hourTo';
                            break;
                        }
                    case 'weekDay':
                        {
                           $orderColumn = 'e.weekDay';
                            break;
                        }
                    case 'shiftDate':
                        {
                            $orderColumn = 'e.shiftDate';
                            break;
                        }
                    case 'overtime':
                        {
                            $orderColumn = 'e.overtime';
                            break;
                        }
                    case 'flexibleHours':
                        {
                            $orderColumn = 'e.flexibleHours';
                            break;
                        }
                    case 'flexitour':
                        {
                           $orderColumn = 'e.flexitour';
                            break;
                        }
                   
                    case 'complex':
                        {
                            $orderColumn = 'c.name';
                            break;
                        }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }
    
}
