<?php

namespace Backend\AdminBundle\Repository;

/**
 * SystemChangeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemChangeLogRepository extends \Doctrine\ORM\EntityRepository
{
}
