<?php

namespace Backend\AdminBundle\Repository;

/**
 * TenantContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TenantContractRepository extends \Doctrine\ORM\EntityRepository
{
}
