<?php

namespace Backend\AdminBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * TenantContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TenantContractRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApiRegister( $email )
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.enabled = 1')
            ->andWhere('a.invitationUserEmail = :email')
            ->andWhere('a.user IS NULL')
            ->andWhere('a.isOwner = false')
            ->setParameter('email', $email)
        ;

        return $qb->getQuery()->getResult();
    }

    public function getApiPropertyInvites( $propertyContractId, $propertyId, $pageId = 1, $limit = 10 )
    {
        $qb = $this->genericApiPropertyInvites($propertyContractId, $propertyId);

        $qb->setFirstResult(($pageId - 1) * $limit)// Offset
            ->setMaxResults($limit)// Limit
            ->orderBy('a.createdAt', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function countApiPropertyInvites($propertyContractId, $propertyId)
    {
        $qb = $this->genericApiPropertyInvites($propertyContractId, $propertyId);
        $qb->select('count(a.id)');
        return $qb->getQuery()->getSingleScalarResult();
    }

    private function genericApiPropertyInvites( $propertyContractId, $propertyId ){
        $qb = $this->createQueryBuilder('a');

        return $qb->select('a, c, p')
            ->innerJoin('a.propertyContract', 'c')
            ->innerJoin('c.property', 'p')
            ->leftJoin('a.user', 'u', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('u', 'a.user'),
                $qb->expr()->eq('u.enabled', '1')
            ))
            ->where('a.enabled = 1')
            ->andWhere('c.enabled = 1')
            ->andWhere('p.enabled = 1')
            ->andWhere('c.id = :propertyContractId')
            ->andWhere('p.id = :propertyId')
            ->andWhere('a.isOwner = false')
            ->setParameter('propertyContractId', $propertyContractId)
            ->setParameter('propertyId', $propertyId)
        ;
    }

    public function getApiProperties($userID)
    {
        $qb = $this->getGenericApiProperty($userID);


        return $qb->getQuery()->getResult();
    }

    public function getGenericApiProperty($userID)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('tc, s, pt, p, pc')

            ->innerJoin('tc.propertyContract', 'pc', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('pc', 'tc.propertyContract'),
                $qb->expr()->eq('pc.enabled', '1')
            ))

            ->leftJoin('pc.property', 'p', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('p', 'pc.property'),
                $qb->expr()->eq('p.enabled', '1')
            ))

            ->leftJoin('p.complexSector', 's', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('s', 'p.complexSector'),
                $qb->expr()->eq('s.enabled', '1')
            ))
            ->leftJoin('p.propertyType', 'pt', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('pt', 'a.propertyType'),
                $qb->expr()->eq('pt.enabled', '1')
            ))


            ->where('tc.enabled = 1')
            ->andWhere('tc.user = :userID')
            ->setParameter('userID', $userID)
            ->orderBy('p.createdAt', 'ASC');

        return $qb;
    }


    public function countApiProperties($user)
    {
        $qb = $this->createQueryBuilder('tc')
            ->select('count(tc.id)')
            ->where('tc.enabled = 1')
            ->andWhere('tc.user = :user')
            ->setParameter('user', $user);

        return $qb->getQuery()->getSingleScalarResult();
    }

}
