<?php

namespace Backend\AdminBundle\Repository;

/**
 * TicketChangeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketChangeLogRepository extends \Doctrine\ORM\EntityRepository
{
}
