<?php

namespace Backend\AdminBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * TicketCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketCommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApiCountPerTickets( $ids )
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('t.id as id, count(a.id) as count')
            ->innerJoin('a.ticket', 't')
            ->where('a.enabled = 1')
            ->andWhere('t.enabled = 1')
            ->groupBy('t.id');

        if ( count( $ids ) > 0 ) {
            $qb->andWhere($qb->expr()->in('t.id', $ids));
        }

        return $qb->getQuery()->getArrayResult();
    }

    public function getApiSingleTicketComments ($ticketId) {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a, t, u, l')
            ->innerJoin('a.ticket', 't')
            ->leftJoin('a.createdBy', 'u', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('u', 'a.createdBy'),
                $qb->expr()->eq('u.enabled', '1')
            ))
            ->leftJoin('a.likedBy', 'l', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('l', 'a.likedBy'),
                $qb->expr()->eq('l.enabled', '1')
            ))
            ->where('a.enabled = 1')
            ->andWhere('t.enabled = 1')
            ->andWhere('t.id = :ticket_id')
            ->setParameter('ticket_id', $ticketId)
            ->orderBy('a.createdAt', 'ASC');

        return $qb->getQuery()->getResult();
    }

}
