<?php

namespace Backend\AdminBundle\Repository;

/**
 * TicketFilePhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketFilePhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
