<?php

namespace Backend\AdminBundle\Repository;

/**
 * TicketStatusLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketStatusLogRepository extends \Doctrine\ORM\EntityRepository
{
}
