<?php

namespace Backend\AdminBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApiFeed($objProperty, $categoryId, $user, $pageId = 1, $limit = 10)
    {
        $complexID = $objProperty->getComplex()->getId();
        $sectorID = $objProperty->getComplexSector()->getId();
        $propertyID = $objProperty->getId();

        $qb = $this->queryBuilderForApiFeed($complexID, $sectorID, $propertyID, $categoryId, $user);

        $qb->select('a, tc, tt, ts, u, car, cars, ca, p')
            ->setFirstResult(($pageId - 1) * $limit)// Offset
            ->setMaxResults($limit)// Limit
            ->orderBy('a.createdAt', 'DESC');

        //$query=$qb->getQuery();
        // SHOW SQL:
        //echo $query->getSQL();
        // Show Parameters:
        //echo $query->getParameters();die;

        return $qb->getQuery()->getResult();
    }

    public function countApiFeed($objProperty, $categoryId, $user)
    {

        $complexID = $objProperty->getComplex()->getId();
        $sectorID = $objProperty->getComplexSector()->getId();
        $propertyID = $objProperty->getId();

        $qb = $this->queryBuilderForApiFeed($complexID, $sectorID, $propertyID, $categoryId, $user);
        $qb->select('count(a.id)');
        return $qb->getQuery()->getSingleScalarResult();
    }

    private function queryBuilderForApiFeed($complexID, $sectorID, $propertyID, $categoryId, $user)
    {

         $qb = $this->genericTicketQueryBuilder()
            ->andWhere('p.id = :property')

            //->andWhere('a.createdBy = :user')
            //->setParameter('user', $user)
                ///share
            ->orWhere("a.ticketType = :share AND a.complex = :complex")
             ->setParameter('share', 2)

             ///notifications to a sector
             ->orWhere("a.ticketType = :notification AND a.complex = :complex AND a.complexSector = :sector AND a.property = :property")
             ->orWhere("a.ticketType = :notification AND a.complex = :complex AND a.complexSector = :sector AND a.property IS NULL")
             ->orWhere("a.ticketType = :notification AND a.complex = :complex AND a.complexSector IS NULL AND a.property IS NULL")

             ->setParameter('notification', 4)
             ->setParameter('complex', $complexID)
             ->setParameter('sector', $sectorID)
             ->setParameter('property', $propertyID)

            ;

            if(intval($categoryId) != 0){
                $qb->andWhere('tc.id = :cat_id');
                $qb->setParameter('cat_id', $categoryId);
            }

         return $qb;


    }

    public function getApiSingleTicket($ticketId)
    {
        $qb = $this->genericTicketQueryBuilder()
            ->andWhere('a.id = :ticket_id')
            ->setParameter('ticket_id', $ticketId);

        return $qb->getQuery()->getOneOrNullResult();
    }

    private function genericTicketQueryBuilder()
    {
        $qb = $this->createQueryBuilder('a');

         $qb->select('a, tc, tt, ts, u, car, cars, ca, p')
            ->leftJoin('a.ticketCategory', 'tc', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('tc', 'a.ticketCategory'),
                $qb->expr()->eq('tc.enabled', '1')
            ))
            ->leftJoin('a.ticketType', 'tt', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('tt', 'a.ticketType'),
                $qb->expr()->eq('tt.enabled', '1')
            ))
            ->leftJoin('a.ticketStatus', 'ts', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('ts', 'a.ticketStatus'),
                $qb->expr()->eq('ts.enabled', '1')
            ))
            ->leftJoin('a.createdBy', 'u', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('u', 'a.createdBy'),
                $qb->expr()->eq('u.enabled', '1')
            ))
            ->leftJoin('a.commonAreaReservation', 'car', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('car', 'a.commonAreaReservation'),
                $qb->expr()->eq('car.enabled', '1')
            ))
            ->leftJoin('car.commonArea', 'ca', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('ca', 'car.commonArea'),
                $qb->expr()->eq('ca.enabled', '1')
            ))
            ->leftJoin('car.commonAreaReservationStatus', 'cars', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('cars', 'car.commonAreaReservationStatus'),
                $qb->expr()->eq('cars.enabled', '1')
            ))
            ->leftJoin('a.property', 'p', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('p', 'a.property'),
                $qb->expr()->eq('p.enabled', '1')
            ))
            ->where('a.enabled = 1');

         return $qb;
    }



    public function getOldSharedProperties(){

        $sql = "	SELECT 	id
                    FROM 	ticket
                    WHERE   DATEDIFF(CURDATE(),STR_TO_DATE(created_at, '%Y-%m-%d')) > 30";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();
        $arrReturn = array();
        foreach ($execute as $row) {
            $arrReturn[$row["id"]] = $row["id"];
        }

        return $arrReturn;

    }




    public function getRequiredDTData($start, $length, $orders, $search, $columns, $filterComplex, $filterProperty = null)
    {
        //print "entra";die;
        // Create Main Query
        $query = $this->createQueryBuilder('e');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        //ENABLED
        $query->andWhere("e.enabled = 1");
        $countQuery->andWhere("e.enabled = 1");


        // Create inner joins

        //complex
        $query->join('e.complex', 'c');
        $countQuery->join('e.complex', 'c');

        //property
        $query->join('e.property', 'p');
        $countQuery->join('e.property', 'p');


        //ticket category
        $query->join('e.ticketCategory', 'tc');
        $countQuery->join('e.ticketCategory', 'tc');

        //ticket status
        $query->join('e.ticketStatus', 'ts');
        $countQuery->join('e.ticketStatus', 'ts');

        //tenantContract
        $query->join('e.tenantContract', 'tenantc');
        $countQuery->join('e.tenantContract', 'tenantc');

        //propertyContract
        $query->join('tenantc.propertyContract', 'pc');
        $countQuery->join('tenantc.propertyContract', 'pc');



        if ($filterComplex != null) {
            $query->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
            $countQuery->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
        }

        if($filterProperty != null){
            $query->andWhere('p.id = :propertyID')->setParameter('propertyID', $filterProperty);
            $countQuery->andWhere('p.id = :propertyID')->setParameter('propertyID', $filterProperty);

        }


        //EXCLUDE FROM LIST THE RESERVATION AND SHARE
        $query->andWhere('e.ticketType = :ttype')->setParameter('ttype', 1);
        $countQuery->andWhere('e.ticketType = :ttype')->setParameter('ttype', 1);


        // Fields Search
        foreach ($columns as $key => $column) {
            if ($column['search']['value'] != '') {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch ($column['name']) {
                    case 'id':
                        {
                            $searchQuery = 'e.id =' . $searchItem;
                            break;
                        }
                    case 'title':
                        {
                            $searchQuery = 'e.title LIKE \'%' . $searchItem . '%\'';
                            break;
                        }

                    case 'contract':
                        {
                            $searchQuery = 'pc.id LIKE \'%' . $searchItem . '%\'';
                            break;
                        }

                    case 'category':
                        {
                            $searchQuery = 'tc.name LIKE \'%' . $searchItem . '%\'';
                            break;
                        }


                }


                if ($searchQuery !== null) {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order) {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order) {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '') {
                $orderColumn = null;

                switch ($order['name']) {
                    case 'id':
                        {
                            $orderColumn = 'e.id';
                            break;
                        }
                    case 'title':
                        {
                            $orderColumn = 'e.title';
                            break;
                        }
                    case 'type':
                        {
                            $orderColumn = 'e.isPublic';
                            break;
                        }
                    case 'category':
                        {
                            $orderColumn = 'tc.name';
                            break;
                        }
                    case 'status':
                        {
                            $orderColumn = 'ts.nameEN';
                            break;
                        }
                    case 'elapsed':
                        {
                            $orderColumn = 'e.title';
                            break;
                        }

                    case 'contract':
                        {
                            $orderColumn = 'pc.id';
                            break;
                        }

                }

                if ($orderColumn !== null) {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" => $results,
            "countResult" => $countResult
        );
    }



    public function getNotificationsDTData($start, $length, $orders, $search, $columns, $filterComplex)
    {
        //print "entra";die;
        // Create Main Query
        $query = $this->createQueryBuilder('e');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        //ENABLED
        $query->andWhere("e.enabled = 1");
        $countQuery->andWhere("e.enabled = 1");


        // Create inner joins

        //complex
        $query->join('e.complex', 'c');
        $countQuery->join('e.complex', 'c');

        //complex
        $query->leftJoin('e.complexSector', 's');
        $countQuery->leftJoin('e.complexSector', 's');


        //property
        $query->leftJoin('e.property', 'p');
        $countQuery->leftJoin('e.property', 'p');


        //ticket category
        $query->join('e.ticketCategory', 'tc');
        $countQuery->join('e.ticketCategory', 'tc');


        if ($filterComplex != null) {
            $query->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
            $countQuery->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
        }


        //JUST THE NOTIFICATIONS
        $query->andWhere('e.ticketType = :ttype')->setParameter('ttype', 4);
        $countQuery->andWhere('e.ticketType = :ttype')->setParameter('ttype', 4);


        // Fields Search
        foreach ($columns as $key => $column) {
            if ($column['search']['value'] != '') {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch ($column['name']) {
                    case 'id':
                    {
                        $searchQuery = 'e.id =' . $searchItem;
                        break;
                    }
                    case 'title':
                    {
                        $searchQuery = 'e.title LIKE \'%' . $searchItem . '%\'';
                        break;
                    }

                    case 'sector':
                    {
                        $searchQuery = 's.name LIKE \'%' . $searchItem . '%\'';
                        break;
                    }


                    case 'property':
                    {
                        $searchQuery = 'p.propertyNumber LIKE \'%' . $searchItem . '%\'';
                        break;
                    }

                    case 'category':
                    {
                        $searchQuery = 'tc.name LIKE \'%' . $searchItem . '%\'';
                        break;
                    }


                }


                if ($searchQuery !== null) {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order) {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order) {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '') {
                $orderColumn = null;

                switch ($order['name']) {
                    case 'id':
                    {
                        $orderColumn = 'e.id';
                        break;
                    }
                    case 'title':
                    {
                        $orderColumn = 'e.title';
                        break;
                    }

                    case 'category':
                    {
                        $orderColumn = 'tc.name';
                        break;
                    }

                    case 'sector':
                    {
                        $orderColumn = 's.name';
                        break;
                    }

                    case 'property':
                    {
                        $orderColumn = 'p.propertyNumber';
                        break;
                    }


                }

                if ($orderColumn !== null) {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" => $results,
            "countResult" => $countResult
        );
    }


}
