<?php

namespace Backend\AdminBundle\Repository;

use Backend\AdminBundle\Entity\TicketCategory;
use Doctrine\ORM\Query\Expr\Join;

/**
 * TicketCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketCategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApiTicketCategories($complexId, $pageId = 1, $limit = 10)
    {
        $qb = $this->queryBuilderForApiTicketCategories($complexId);

        $qb->select('a, c, i')
            ->setFirstResult(($pageId - 1) * $limit)// Offset
            ->setMaxResults($limit)// Limit
            ->orderBy('a.createdAt', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function countApiTicketCategories($complexId)
    {
        $qb = $this->queryBuilderForApiTicketCategories($complexId);
        $qb->select('count(a.id)');
        return $qb->getQuery()->getSingleScalarResult();
    }

    private function queryBuilderForApiTicketCategories($complexId)
    {
        $qb = $this->createQueryBuilder('a');
        return $qb->select('a')
            ->leftJoin('a.complex', 'c', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('c', 'a.complex'),
                $qb->expr()->eq('c.enabled', '1')
            ))
            ->leftJoin('a.icon', 'i', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('i', 'a.icon'),
                $qb->expr()->eq('i.enabled', '1')
            ))
            ->where('a.enabled = 1')
            //->andWhere('a.isGeneral = 1')
            ->andWhere('c.id = :com_id')
            ->setParameter('com_id', $complexId);
    }



    public function getRequiredDTData($start, $length, $orders, $search, $columns, $otherConditions, $filterComplex)
    {
        //print "entra";die;
        // Create Main Query
        $query = $this->createQueryBuilder('e');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        // Create inner joins
        $query->join('e.complex', 'c');
        $countQuery->join('e.complex', 'c');


        //ENABLED
        $query->andWhere("e.enabled = 1");
        $countQuery->andWhere("e.enabled = 1");

        $query->andWhere("c.enabled = 1");
        $countQuery->andWhere("c.enabled = 1");


        if($filterComplex != null){
            $query->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
            $countQuery->andWhere('c.id IN (:arrComplexID)')->setParameter('arrComplexID', $filterComplex);
        }
        
        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                        {
                            $searchQuery = 'e.id ='. $searchItem;
                            break;
                        }
                    case 'name':
                        {
                            $searchQuery = 'e.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'complex':
                        {
                            $searchQuery = 'c.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }


                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                        {
                            $orderColumn = 'e.id';
                            break;
                        }
                    case 'name':
                        {
                            $orderColumn = 'e.name';
                            break;
                        }

                    case 'complex':
                        {
                            $orderColumn = 'c.name';
                            break;
                        }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }


    public function loadTicketCategories($complex){


        //OJO DEBE DE SER SEGUN EL IDIOMA DE SU COMPLEX/BUSINESS
        //general fixes
        //security
        //Billing
        //cleaning
        //electricity
        //water
        //neighborhood
        $em = $this->getEntityManager();

        /*
         *  General Fixes
            Security
            Utilities
            Cleaning
            Common Area
            Maintenance
            Complaints
            Emergencies
            Visits

         *
         */


        $arrDefault = array(
            
                    array("f7d9" => array("en" => "Fixes", "es" => "Reparaciones", "hexa" => "#ff0044")),
                    array("f3ed" => array("en" => "Security", "es" => "Seguridad","hexa" => "#68386c")) ,
                    array("f552" =>array("en" => "Utilities", "es" => "Servicios","hexa" => "#a22532")) ,
                    array("f51a" => array("en" => "Cleaning", "es" => "Limpieza","hexa" => "#8b9bb4")),
                    array("f78c" => array("en" => "Common Area", "es" => "Área común","hexa" => "#1bb954")),
                    array("f0ad" => array("en" => "Maintenance", "es" => "Mantenimiento","hexa" => "#265d42")),
                    array("f071" => array("en" => "Complaints", "es" => "Reclamos","hexa" => "#f77622")),
                    array("f0f9" => array("en" => "Emergencies", "es" => "Emergencias","hexa" => "#8c1091")),
                    array("f2c2" => array("en" => "Visits", "es" => "Visitas", "hexa" => "#10bba9"))
                            );


        $repositoryIcon = $em->getRepository('BackendAdminBundle:Icon');
        $repositoryComplex = $em->getRepository('BackendAdminBundle:Complex');
        $objComplex = $repositoryComplex->find($complex);

        $defaultIcons = $repositoryIcon->findByIsGeneral(1);

        $myLocale = $objComplex->getGeoState()->getGeoCountry()->getLocale();

        foreach ($defaultIcons as $icon ){


            $name = $myLocale == "en" ? $icon->getName() : $icon->getNameES();

            $ticketCat = new TicketCategory();
            $ticketCat->setName($name);
            $ticketCat->setDescription($name);
            $ticketCat->setComplex($objComplex);
            $ticketCat->setEnabled(1);
            $gtmNow = gmdate("Y-m-d H:i:s");

            $ticketCat->setCreatedAt(new \DateTime($gtmNow));
            $ticketCat->setUpdatedAt(new \DateTime($gtmNow));
            $ticketCat->setCreatedBy(null);
            $ticketCat->setUpdatedBy(null);


            $ticketCat->setIsGeneral(1);

            $ticketCat->setIcon($icon);
            $ticketCat->setColor($icon->getColor());

            $em->persist($ticketCat);


        }
        $em->flush();



    }





}
