<?php

namespace Backend\AdminBundle\Repository;

/**
 * TicketCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
