<?php

namespace Backend\AdminBundle\Repository;

/**
 * TicketCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketCommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApiRepliesQuantities( $ids )
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a, t')
            ->innerJoin('a.ticket', 't')
            ->where('a.enabled = 1')
            ->orderBy('a.createdAt', 'ASC');

        if ( count( $ids ) > 0 ) {
            $qb->andWhere($qb->expr()->in('t.id', $ids));
        } else {
            $qb->andWhere($qb->expr()->in('t.id', array( 0 )));
        }

        return $qb->getQuery()->getResult();
    }

}
