<?php

namespace Backend\AdminBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApiFeed($propertyId, $categoryId, $user, $pageId = 1, $limit = 10)
    {
        $qb = $this->queryBuilderForApiFeed($propertyId, $categoryId, $user);

        $qb->select('a, tc, tt, ts, u, car, cars, ca, p')
            ->setFirstResult(($pageId - 1) * $limit)// Offset
            ->setMaxResults($limit)// Limit
            ->orderBy('a.createdAt', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function countApiFeed($propertyId, $categoryId, $user)
    {
        $qb = $this->queryBuilderForApiFeed($propertyId, $categoryId, $user);
        $qb->select('count(a.id)');
        return $qb->getQuery()->getSingleScalarResult();
    }

    private function queryBuilderForApiFeed($propertyId, $categoryId, $user)
    {
        return $qb = $this->genericTicketQueryBuilder()
            ->andWhere('p.id = :prop_id')
            ->andWhere('tc.id = :cat_id')
            ->andWhere('a.createdBy = :user')
            ->setParameter('user', $user)
            ->setParameter('prop_id', $propertyId)
            ->setParameter('cat_id', $categoryId);
    }

    public function getApiSingleTicket($ticketId)
    {
        $qb = $this->genericTicketQueryBuilder()
            ->andWhere('a.id = :ticket_id')
            ->setParameter('ticket_id', $ticketId);

        return $qb->getQuery()->getOneOrNullResult();
    }

    private function genericTicketQueryBuilder()
    {
        $qb = $this->createQueryBuilder('a');

        return $qb->select('a, tc, tt, ts, u, car, cars, ca, p')
            ->leftJoin('a.ticketCategory', 'tc', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('tc', 'a.ticketCategory'),
                $qb->expr()->eq('tc.enabled', '1')
            ))
            ->leftJoin('a.ticketType', 'tt', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('tt', 'a.ticketType'),
                $qb->expr()->eq('tt.enabled', '1')
            ))
            ->leftJoin('a.ticketStatus', 'ts', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('ts', 'a.ticketStatus'),
                $qb->expr()->eq('ts.enabled', '1')
            ))
            ->leftJoin('a.createdBy', 'u', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('u', 'a.createdBy'),
                $qb->expr()->eq('u.enabled', '1')
            ))
            ->leftJoin('a.commonAreaReservation', 'car', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('car', 'a.commonAreaReservation'),
                $qb->expr()->eq('car.enabled', '1')
            ))
            ->leftJoin('car.commonArea', 'ca', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('ca', 'car.commonArea'),
                $qb->expr()->eq('ca.enabled', '1')
            ))
            ->leftJoin('car.commonAreaReservationStatus', 'cars', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('cars', 'car.commonAreaReservationStatus'),
                $qb->expr()->eq('cars.enabled', '1')
            ))
            ->leftJoin('a.property', 'p', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('p', 'a.property'),
                $qb->expr()->eq('p.enabled', '1')
            ))
            ->where('a.enabled = 1');
    }



    public function getOldSharedProperties(){

        $sql = "	SELECT 	id
                    FROM 	ticket
                    WHERE   DATEDIFF(CURDATE(),STR_TO_DATE(created_at, '%Y-%m-%d')) > 30";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();
        $arrReturn = array();
        foreach ($execute as $row) {
            $arrReturn[$row["id"]] = $row["id"];
        }

        return $arrReturn;

    }

}
