<?php

namespace Backend\AdminBundle\Repository;

/**
 * TicketFollowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketFollowerRepository extends \Doctrine\ORM\EntityRepository
{
}
