<?php

namespace Backend\AdminBundle\Repository;

/**
 * UserBusinessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBusinessRepository extends \Doctrine\ORM\EntityRepository
{
}
