<?php

namespace Backend\AdminBundle\Repository;

/**
 * UserComplexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserComplexRepository extends \Doctrine\ORM\EntityRepository
{


}
