<?php

namespace Backend\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Session\Session;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{



    public function getRequiredDTData($start, $length, $orders, $search, $columns, $otherConditions)
    {
        // Create Main Query
        $query = $this->createQueryBuilder('u');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('u');
        $countQuery->select('COUNT(u)');

        // Create inner joins
        $query->join('u.role', 'r');
        $countQuery->join('u.role', 'r');

        if(!empty($otherConditions)){
            $query->andWhere("u.business = ".$otherConditions["business"]);
            $countQuery->andWhere("u.business = ".$otherConditions["business"]);

        }


        //ENABLED
        $query->andWhere("u.enabled = 1");
        $countQuery->andWhere("u.enabled = 1");
        $query->andWhere("r.enabled = 1");
        $countQuery->andWhere("r.enabled = 1");



        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                        {
                            $searchQuery = 'u.id ='. $searchItem;
                            break;
                        }
                    case 'email':
                        {
                            $searchQuery = 'u.email LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                    case 'role':
                        {
                            $searchQuery = 'r.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                        {
                            $orderColumn = 'u.id';
                            break;
                        }

                    case 'email':
                        {
                            $orderColumn = 'u.email';
                            break;
                        }

                    case 'role':
                        {
                            $orderColumn = 'r.name';
                            break;
                        }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }
		
}
