<?php

namespace Backend\AdminBundle\Repository;

use Backend\AdminBundle\Controller\RestController;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;
use Symfony\Component\HttpFoundation\Session\Session;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApiPostFaq($businessId) {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a')
            ->leftJoin('a.business', 'b', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('b', 'a.business'),
                $qb->expr()->eq('b.enabled', '1')
            ))
            ->leftJoin('a.role', 'r', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('r', 'a.role'),
                $qb->expr()->eq('r.enabled', '1')
            ))
            ->where('a.enabled = 1')
            ->andWhere('b.id = :businessId')
            ->andWhere('r.id = :roleId')
            ->setParameter(':businessId', $businessId)
            ->setParameter(':roleId', RestController::USER_ADMIN_ROLE_ID)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }



    public function getRequiredDTData($start, $length, $orders, $search, $columns, $otherConditions)
    {
        // Create Main Query
        $query = $this->createQueryBuilder('u');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('u');
        $countQuery->select('COUNT(u)');

        // Create inner joins
        $query->join('u.role', 'r');
        $countQuery->join('u.role', 'r');

        if(!empty($otherConditions)){

            if(isset($otherConditions["business"])){
                $query->andWhere("u.business = ".$otherConditions["business"]);
                $countQuery->andWhere("u.business = ".$otherConditions["business"]);

            }
            else{
                $query->andWhere("u.id IN(".$otherConditions.") ");
                $countQuery->andWhere("u.id IN(".$otherConditions.") ");
            }

        }


        //ENABLED
        $query->andWhere("u.enabled = 1");
        $countQuery->andWhere("u.enabled = 1");
        $query->andWhere("r.enabled = 1");
        $countQuery->andWhere("r.enabled = 1");



        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                        {
                            $searchQuery = 'u.id ='. $searchItem;
                            break;
                        }
                    case 'email':
                        {
                            $searchQuery = 'u.email LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                    case 'role':
                        {
                            $searchQuery = 'r.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                        {
                            $orderColumn = 'u.id';
                            break;
                        }

                    case 'email':
                        {
                            $orderColumn = 'u.email';
                            break;
                        }

                    case 'role':
                        {
                            $orderColumn = 'r.name';
                            break;
                        }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }



    public function getUserByBusinessComplex($userID, $businessID)
    {

        $strFilter = "";
        if($userID != 0){
            $strFilter = " AND uc.user_id = {$userID} ";
        }


        $sql = "	SELECT  DISTINCT(uc.user_id) id
					FROM    business b    
					    INNER JOIN complex c ON(c.business_id = b.id)
					    INNER JOIN user_complex uc ON(uc.complex_id = c.id)
					    INNER JOIN user u ON (uc.user_id = u.id)
					WHERE   b.id = {$businessID}
					AND     u.role_id != 1
					{$strFilter}
					ORDER BY c.name";
        //AND     u.role_id != 1 // EXCLUDE ADMIN FOR THE SUPERVISORS

        //print $sql;die;

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();
        $arrReturn = array();

        foreach ($execute as $row) {
            $arrReturn[$row["id"]] = $row["id"];
        }

        return $arrReturn;

    }




    public function getStats($complexID){

        $arrReturn = array();

        //total
        $countUsers = "    SELECT  COUNT(tc.id) quantity
                            FROM 	user u
                                INNER JOIN tenant_contract tc ON (u.id = tc.user_id)
                                INNER JOIN property_contract pc ON (pc.id = tc.property_contract_id)
                                INNER JOIN property p ON (p.id = pc.property_id)
                            WHERE   u.enabled = 1
                            AND     p.complex_id = {$complexID}
                            AND      pc.is_active = 1
                            AND     tc.enabled = 1";
        //AND     t.complex_id = {$complexID}

        $stmt = $this->getEntityManager()->getConnection()->prepare($countUsers);
        $stmt->execute();
        $execute = $stmt->fetchAll();

        $arrReturn["total"] = $execute[0]["quantity"];
        $arrReturn["tenants"] = $execute[0]["quantity"];

        //owner
        $countOwners = "    SELECT  COUNT(tc.id) quantity
                            FROM 	user u
                                INNER JOIN tenant_contract tc ON (u.id = tc.user_id)
                                INNER JOIN property_contract pc ON (pc.id = tc.property_contract_id)
                                INNER JOIN property p ON (p.id = pc.property_id)
                            WHERE   u.enabled = 1
                            AND     p.complex_id = {$complexID}
                            AND      pc.is_active = 1
                            AND     tc.main_tenant = 1
                            AND     tc.enabled = 1
                            AND     tc.owner_id IS NOT NULL";
        //AND     t.complex_id = {$complexID}

        $stmt = $this->getEntityManager()->getConnection()->prepare($countOwners);
        $stmt->execute();
        $execute = $stmt->fetchAll();

        $arrReturn["owners"] = $execute[0]["quantity"];


        //TEAM MEMBERS

        //total
        $countMembers = "    SELECT  COUNT(u.id) quantity
                            FROM 	user u
                                INNER JOIN complex c ON (c.id = {$complexID})
                                INNER JOIN business b ON (b.id = c.business_id)
                            WHERE   u.enabled = 1
                            AND     u.role_id IN(1,2,3)
                            ";
        //AND     t.complex_id = {$complexID}

        $stmt = $this->getEntityManager()->getConnection()->prepare($countMembers);
        $stmt->execute();
        $execute = $stmt->fetchAll();

        $arrReturn["members"] = intval($execute[0]["quantity"]);

        $countManagers = "    SELECT  COUNT(u.id) quantity
                                FROM 	user u
                                    INNER JOIN complex c ON (c.id = {$complexID})
                                    INNER JOIN business b ON (b.id = c.business_id)
                                WHERE   u.enabled = 1
                                AND     u.role_id IN(1,2)
                                ";
        //AND     t.complex_id = {$complexID}

        $stmt = $this->getEntityManager()->getConnection()->prepare($countManagers);
        $stmt->execute();
        $execute = $stmt->fetchAll();

        $arrReturn["managers"] = intval($execute[0]["quantity"]);
        $arrReturn["superv"] = $arrReturn["members"] - $arrReturn["managers"];


        return $arrReturn;

    }

		
}
