<?php

namespace Backend\AdminBundle\Repository;

/**
 * UserAgreementPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAgreementPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
