<?php

namespace Backend\AdminBundle\Repository;

/**
 * UserComplexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserComplexRepository extends \Doctrine\ORM\EntityRepository
{


    //cleanUserComplex
    public function cleanUserComplex($userID){

        $sql = "	DELETE
					FROM 	user_complex
                    WHERE 	user_id = '{$userID}'";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        //return $stmt->fetchAll();

    }






}
