<?php

namespace Backend\AdminBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * UserNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNotificationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApiInbox($user, $pageId = 1, $limit = 10)
    {
        $qb = $this->queryBuilderForApiInbox($user);

        $qb->select('a, u, t, nt')
            ->setFirstResult(($pageId - 1) * $limit)// Offset
            ->setMaxResults($limit)// Limit
            ->orderBy('a.createdAt', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function countApiInbox($user)
    {
        $qb = $this->queryBuilderForApiInbox($user);

        $qb->select('count(a.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function countApiInboxUnread($user)
    {
        $qb = $this->queryBuilderForApiInbox($user);
        $qb->andWhere("a.isRead = 0");

        $qb->select('count(a.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }

    private function queryBuilderForApiInbox($user)
    {
        $qb = $this->createQueryBuilder('a');
        return $qb->select('a')
            ->leftJoin('a.createdBy', 'u', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('u', 'a.createdBy'),
                $qb->expr()->eq('u.enabled', '1')
            ))
            ->leftJoin('u.role', 'ur', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('ur', 'u.role'),
                $qb->expr()->eq('ur.enabled', '1')
            ))
            ->leftJoin('a.notificationType', 'nt', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('nt', 'a.notificationType'),
                $qb->expr()->eq('nt.enabled', '1')
            ))
            ->leftJoin('a.ticket', 't', Join::WITH, $qb->expr()->andX(
                $qb->expr()->eq('t', 'a.ticket'),
                $qb->expr()->eq('t.enabled', '1')
            ))
            ->where('a.enabled = 1')
            ->andWhere('a.sentTo = :user')
            ->setParameter('user', $user);
    }



    public function getRequiredDTData($start, $length, $orders, $search, $columns, $otherConditions)
    {
        // Create Main Query
        $query = $this->createQueryBuilder('e');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        //ENABLED
        $query->andWhere("e.enabled = 1");
        $countQuery->andWhere("e.enabled = 1");

        //ticket category
        $query->join('e.ticketCategory', 'tc');
        $countQuery->join('e.ticketCategory', 'tc');


        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                        {
                            $searchQuery = 'e.id ='. $searchItem;
                            break;
                        }
                    case 'title':
                        {
                            $searchQuery = 'e.title LIKE \'%'.$searchItem.'%\'';
                            break;
                        }
                    case 'category':
                        {
                            $searchQuery = 'tc.name LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                    case 'sent':
                        {
                            $searchQuery = 'e.scheduledTime LIKE \'%'.$searchItem.'%\'';
                            break;
                        }

                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                        {
                            $orderColumn = 'e.id';
                            break;
                        }
                    case 'title':
                        {
                            $orderColumn = 'e.title';
                            break;
                        }
                    case 'category':
                        {
                            $orderColumn = 'tc.name';
                            break;
                        }

                    case 'sent':
                        {
                            $orderColumn = 'e.scheduledTime';
                            break;
                        }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }


    public function getNotification($userID, $complexFilters){

        $arrReturn = array();
        $strFilter = "";
        $in = "";
        if(!empty($complexFilters)){
            foreach ($complexFilters as $key => $value) {
                $in .= $in == "" ? $value : ",".$value;
            }

        }
        $strFilter = " AND ca.complex_id IN({$in}) ";
        //var_dump($in);die;

        if($in == ""){
            return $arrReturn;
        }

        $sql = "	SELECT 	n.id, n.created_at, n.title, n.description, n.notification_type_id, 
	                        car.id reservation_id, t.id ticket_id
                    FROM 	user_notification n
                        LEFT JOIN common_area_reservation car ON (n.common_area_reservation_id = car.id)
                        LEFT JOIN common_area ca ON (car.common_area_id = ca.id {$strFilter})
                        LEFT JOIN ticket t ON (n.ticket_id = t.id)
                    
                    WHERE   n.notification_type_id IN(1,2)
                    AND     n.is_read = 0
                    AND     n.sent_to = {$userID}
                    
                    ORDER BY n.id";
        //AND     n.sent_to = {$userID}

        //var_dump($sql);die;


        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();

        foreach ($execute as $row) {
            $arrReturn[$row["id"]] = array();
            $arrReturn[$row["id"]]["title"] = $row["title"];
            $arrReturn[$row["id"]]["description"] = $row["description"];
            $arrReturn[$row["id"]]["created_at"] = $row["created_at"];
            $arrReturn[$row["id"]]["reservation_id"] = $row["reservation_id"];
            $arrReturn[$row["id"]]["ticket_id"] = $row["ticket_id"];
            $arrReturn[$row["id"]]["type"] = $row["notification_type_id"];
        }

        return $arrReturn;

    }

    //markAllNotificationRead

    public function markAllNotificationRead($userID, $complexFilters){

        $arrReturn = array();
        $strFilter = "";
        $in = "";
        if(!empty($complexFilters)){
            foreach ($complexFilters as $key => $value) {
                $in .= $in == "" ? $value : ",".$value;
            }

        }
        $strFilter = " AND ca.complex_id IN({$in}) ";

        //COMMON AREA RESERVATION
        $sql = "	SELECT 	n.id
                    FROM 	user_notification n
                        LEFT JOIN common_area_reservation car ON (n.common_area_reservation_id = car.id)
                        LEFT JOIN common_area ca ON (car.common_area_id = ca.id)
                        LEFT JOIN ticket ON (n.ticket_id = t.id)
                    WHERE n.notification_type_id IN(1,2)
                    AND n.is_read = 0
                    $strFilter
                    ORDER BY n.id";


        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();

        foreach ($execute as $row) {

            $tempID = intval($row["id"]);
            $sqlUpdate = "  UPDATE  user_notification
                            SET     is_read = 1
                            WHERE   id = {$tempID}";

            $stmt = $this->getEntityManager()->getConnection()->prepare($sqlUpdate);
            $stmt->execute();

        }




        return true;

    }


}
